import { describe, expect, it } from "vitest"
import {
  buildHtmlWordClipboardPayload,
  buildNormalizedExportFromLiveOutput,
  buildSeoFromBootstrap,
  buildTaskDocxExportModel,
  copyComponentsToClipboard,
  exportBlocksToClipboardHtml,
  MAIN_BRIEFING_COMPONENT_ID,
  mapHtmlHeadingTagToDocxLevel,
  renderComponentToClipboardHtml,
  renderComponentsToClipboardHtml,
  renderComponentToDocxHtml,
  renderBlocksToPlainText,
  resolveCurrentComponentForExport,
  type ExportComponentOutput,
  type ExportOutputBlock,
} from "../features/tasks/utils/task-docx-export-model"
import {
  wrapHtmlForWordPressClipboardPaste,
  wrapHtmlForWordClipboardPaste,
  cleanClipboardHtml,
  renderStructuredNodesToClipboardHtml,
  type ExportStructuredNode,
} from "../features/tasks/utils/task-content-export-html"
import type { TaskChannelBootstrapResponse } from "../app/lib/types/task-channel-bootstrap"

function makeBootstrap(params: {
  channelId?: number
  components: Array<{
    task_component_id: string
    briefing_component_id: number
    title: string
    position: number
  }>
  composed: Array<{
    task_component_id: string
    briefing_component_id: number
    title: string
    content_json?: ExportOutputBlock[]
    content_text?: string | null
    position: number
  }>
  seo?: TaskChannelBootstrapResponse["seo"]
}): TaskChannelBootstrapResponse {
  return {
    task_id: 1001,
    channel_id: params.channelId ?? 1,
    channel: { id: params.channelId ?? 1, name: "Blog" },
    briefing: { briefing_type_id: 10, disable_briefing: false },
    seo: params.seo ?? null,
    composed_output: params.composed.map((row) => ({
      task_component_id: row.task_component_id,
      briefing_component_id: row.briefing_component_id,
      task_component_output_id: `out-${row.task_component_id}`,
      title: row.title,
      description: null,
      content_text: row.content_text ?? null,
      content: row.content_json ?? null,
      resolved_content_json: row.content_json ?? null,
      content_json: row.content_json ?? null,
      attachment_map: null,
      attachments: [],
      position: row.position,
      updated_at: "2026-06-23T12:00:00.000Z",
      is_autogenerated: false,
      comment_thread_count: 0,
      open_comment_thread_count: 0,
    })),
    components: params.components.map((row) => ({
      task_component_id: row.task_component_id,
      briefing_component_id: row.briefing_component_id,
      title: row.title,
      description: null,
      selected: true,
      position: row.position,
      template_layer: "task_channel",
      is_ad_hoc: false,
      origin: "task_global",
      global_overridden: false,
      template_title: row.title,
      template_description: null,
      project_template_title: null,
      project_template_description: null,
      component_key: `g:${row.briefing_component_id}`,
      kind: "global",
    })),
    available_components: [],
    meta: { bootstrap_version: 1, fetched_at: "2026-06-23T12:00:00.000Z" },
  }
}

describe("task-docx-export-model", () => {
  it("exports every selected component once with full content_json bodies, FAQ answers, and SEO", () => {
    const bootstrap = makeBootstrap({
      seo: {
        effective: { seo_required: true, seo_source: "project" },
        override: {
          primary_keyword: "materiais de alta resistência",
          secondary_keywords: ["composites", "alloys"],
          seo_required_override: true,
        },
      },
      components: [
        { task_component_id: "tc-intro", briefing_component_id: 1, title: "Intro", position: 0 },
        { task_component_id: "tc-o-que-e", briefing_component_id: 2, title: "O que é?", position: 1 },
        { task_component_id: "tc-vantagens", briefing_component_id: 3, title: "Vantagens", position: 2 },
        { task_component_id: "tc-tipos", briefing_component_id: 4, title: "Que tipos existem?", position: 3 },
        { task_component_id: "tc-faq", briefing_component_id: 5, title: "FAQ", position: 4 },
        { task_component_id: "tc-long", briefing_component_id: 6, title: "Conclusão", position: 5 },
      ],
      composed: [
        {
          task_component_id: "tc-intro",
          briefing_component_id: 1,
          title: "Intro",
          position: 0,
          content_json: [{ type: "paragraph", text: "<p>Intro body about high-strength materials.</p>" }],
        },
        {
          task_component_id: "tc-o-que-e",
          briefing_component_id: 2,
          title: "O que é?",
          position: 1,
          content_json: [{ type: "paragraph", text: "<p>Definition paragraph for high-strength materials.</p>" }],
        },
        {
          task_component_id: "tc-vantagens",
          briefing_component_id: 3,
          title: "Vantagens",
          position: 2,
          content_json: [
            { type: "paragraph", text: "<h3>Advanced Material Integration</h3><p>First advantage detail.</p>" },
            { type: "paragraph", text: "<h3>Cost Savings</h3><p>Second advantage detail.</p>" },
          ],
        },
        {
          task_component_id: "tc-tipos",
          briefing_component_id: 4,
          title: "Que tipos existem?",
          position: 3,
          content_json: [{ type: "paragraph", text: "<p>Types include alloys, composites, and ceramics.</p>" }],
        },
        {
          task_component_id: "tc-faq",
          briefing_component_id: 5,
          title: "FAQ",
          position: 4,
          content_json: [
            { type: "paragraph", text: "<h4>What are high-strength materials?</h4><p>They are engineered materials designed for load-bearing applications.</p>" },
            { type: "paragraph", text: "<h4>Are composites expensive?</h4><p>Costs vary by application and volume.</p>" },
          ],
        },
        {
          task_component_id: "tc-long",
          briefing_component_id: 6,
          title: "Conclusão",
          position: 5,
          content_json: [{ type: "paragraph", text: "<p>" + "Long concluding paragraph. ".repeat(40).trim() + "</p>" }],
        },
        {
          task_component_id: "shared-wrong-id",
          briefing_component_id: MAIN_BRIEFING_COMPONENT_ID,
          title: "Main",
          position: 99,
          content_json: [{ type: "paragraph", text: "<p>Should not replace component bodies.</p>" }],
        },
      ],
    })

    const model = buildTaskDocxExportModel({
      taskTitle: "High-Strength Materials Guide",
      taskMeta: {
        contentTypeTitle: "Blog Article",
        metaTitle: "High-Strength Materials | Guide",
        metaDescription: "Learn about high-strength materials, types, and benefits.",
        keyword: "legacy keyword",
      },
      channels: [{ bootstrap, channelName: "Blog" }],
    })

    expect(model.contentTypeTitle).toBe("Blog Article")
    expect(model.channels).toHaveLength(1)

    const channel = model.channels[0]
    expect(channel.components).toHaveLength(6)
    expect(new Set(channel.components.map((component) => component.id)).size).toBe(6)

    const titles = channel.components.map((component) => component.title)
    expect(titles).toEqual([
      "Intro",
      "O que é?",
      "Vantagens",
      "Que tipos existem?",
      "FAQ",
      "Conclusão",
    ])

    expect(channel.components.every((component) => component.hasContent)).toBe(true)
    expect(channel.components.find((component) => component.title === "O que é?")?.html).toContain("Definition paragraph")
    expect(channel.components.find((component) => component.title === "Vantagens")?.html).toContain("Advanced Material Integration")
    expect(channel.components.find((component) => component.title === "Vantagens")?.html).toContain("Cost Savings")
    expect(channel.components.find((component) => component.title === "FAQ")?.html).toContain("They are engineered materials")
    expect(channel.components.find((component) => component.title === "FAQ")?.html).toContain("Costs vary by application")

    const vantagensHtml = channel.components.find((component) => component.title === "Vantagens")?.html ?? ""
    expect((vantagensHtml.match(/Advanced Material Integration/g) ?? []).length).toBe(1)
    expect((vantagensHtml.match(/Cost Savings/g) ?? []).length).toBe(1)

    expect(channel.seo?.primaryKeyword).toBe("materiais de alta resistência")
    expect(channel.seo?.secondaryKeywords).toEqual(["composites", "alloys"])
    expect(channel.seo?.metaTitle).toBe("High-Strength Materials | Guide")
    expect(channel.seo?.metaDescription).toContain("Learn about high-strength materials")
    expect(channel.seo?.keywordRows.length).toBeGreaterThan(0)
    expect(channel.seo?.keywordRows[0]?.keyword).toBe("materiais de alta resistência")
  })

  it("prefers live component output overrides over stale bootstrap content_text keyed only by briefing id", () => {
    const bootstrap = makeBootstrap({
      components: [
        { task_component_id: "tc-a", briefing_component_id: 10, title: "Section A", position: 0 },
        { task_component_id: "tc-b", briefing_component_id: 11, title: "Section B", position: 1 },
      ],
      composed: [
        {
          task_component_id: "tc-a",
          briefing_component_id: 10,
          title: "Section A",
          position: 0,
          content_text: "<p>Stale shared text</p>",
          content_json: [{ type: "paragraph", text: "<p>Fresh A body</p>" }],
        },
        {
          task_component_id: "tc-b",
          briefing_component_id: 11,
          title: "Section B",
          position: 1,
          content_text: "<p>Stale shared text</p>",
          content_json: [{ type: "paragraph", text: "<p>Fresh B body</p>" }],
        },
      ],
    })

    const liveOutputs = new Map<string, ExportComponentOutput>([
      [
        "t:tc-b",
        {
          content_json: [{ type: "paragraph", text: "<p>Live edited B body</p>" }],
          content_text: "<p>Live edited B body</p>",
          attachments: [],
          attachment_map: null,
        },
      ],
    ])

    const model = buildTaskDocxExportModel({
      taskTitle: "Live override task",
      channels: [
        {
          bootstrap,
          channelName: "Blog",
          liveOverrides: { componentOutputs: liveOutputs },
        },
      ],
    })

    expect(model.channels[0].components).toHaveLength(2)
    expect(model.channels[0].components[0].html).toContain("Fresh A body")
    expect(model.channels[0].components[1].html).toContain("Live edited B body")
    expect(model.channels[0].components[1].html).not.toContain("Stale shared text")
  })

  it("renders WordPress-friendly clipboard HTML with FAQ answers and image placeholders", () => {
    const blocks: ExportOutputBlock[] = [
      { type: "paragraph", text: "<h3>Benefits</h3><p>First benefit paragraph.</p>" },
      { type: "paragraph", text: "<h4>What is it?</h4><p>Answer text for FAQ.</p>" },
      {
        type: "attachment",
        attachment_id: "att-1",
        attachment: {
          id: "att-1",
          file_name: "diagram.png",
          file_path: "tasks/1/diagram.png",
          mime_type: "image/png",
          media_type: "image",
          alt_text: "Process diagram",
          caption: null,
          size: null,
          width: 800,
          height: 600,
          duration_seconds: null,
          sort_order: null,
          uploaded_by: null,
          uploaded_at: null,
          metadata: null,
          public_url: "https://cdn.example.com/diagram.png",
        },
      },
    ]
    const output: ExportComponentOutput = { attachments: [], attachment_map: null }
    const html = exportBlocksToClipboardHtml(blocks, output)
    const plain = renderBlocksToPlainText(blocks, output)

    expect(html).toContain("<h3>Benefits</h3>")
    expect(html).toContain("Answer text for FAQ")
    expect(html).toContain('<img src="https://cdn.example.com/diagram.png"')
    expect(html).toContain('alt="Process diagram"')
    expect(plain).toContain("Answer text for FAQ")
    expect(plain).toContain("[Image: Process diagram]")
  })

  it("buildNormalizedExportFromLiveOutput uses the same blocks for docx and clipboard targets", () => {
    const normalized = buildNormalizedExportFromLiveOutput({
      component: {
        task_component_id: "tc-live",
        briefing_component_id: 12,
        title: "Live section",
        selected: true,
        position: 0,
      },
      output: {
        content_json: [{ type: "paragraph", text: "<p><strong>Bold</strong> intro.</p>" }],
        attachments: [],
        attachment_map: null,
      },
    })

    expect(normalized?.docxHtml).toContain("<strong>Bold</strong>")
    expect(normalized?.clipboardHtml).toContain("<strong>Bold</strong>")
    expect(normalized?.contentText).toContain("Bold intro")
  })

  it("does not prepend internal component labels to docx or clipboard output by default", () => {
    const body = "<h2>What makes a high-tensile material</h2><p>Body text.</p>"
    const component = {
      title: "O que é?",
      html: body,
      clipboardHtml: body,
    }
    expect(renderComponentToDocxHtml(component)).toBe(body)
    expect(renderComponentToClipboardHtml(component)).toBe(body)
    expect(renderComponentToDocxHtml(component)).not.toContain("O que é?")
  })

  it("maps HTML heading tags to exact DOCX heading levels without demotion", () => {
    expect(mapHtmlHeadingTagToDocxLevel("h1")).toBe(1)
    expect(mapHtmlHeadingTagToDocxLevel("h2")).toBe(2)
    expect(mapHtmlHeadingTagToDocxLevel("h3")).toBe(3)
    expect(mapHtmlHeadingTagToDocxLevel("h4")).toBe(4)
    expect(mapHtmlHeadingTagToDocxLevel("p")).toBeNull()
  })

  it("includes keyword search volume and competition in download SEO metadata", () => {
    const metrics = new Map([
      ["high-strength materials", { searchVolume: 1200, competition: 42 }],
      ["composites", { searchVolume: 800, competition: 55 }],
    ])
    const seo = buildSeoFromBootstrap(
      {
        effective: { seo_required: true, seo_source: "project" },
        override: {
          primary_keyword: "high-strength materials",
          secondary_keywords: ["composites"],
          seo_required_override: true,
        },
      },
      { metaTitle: "SEO title", metaDescription: "Meta desc" },
      metrics,
    )
    expect(seo?.keywordRows).toEqual([
      {
        keyword: "high-strength materials",
        isPrimary: true,
        searchVolume: 1200,
        competition: 42,
      },
      {
        keyword: "composites",
        isPrimary: false,
        searchVolume: 800,
        competition: 55,
      },
    ])
  })

  it("wrapHtmlForWordPressClipboardPaste emits clean semantic HTML without Word styles", () => {
    const body = "<h2>What makes a high-tensile material</h2><p>Body paragraph.</p>"
    const document = wrapHtmlForWordPressClipboardPaste(body)

    expect(document).toContain("<!--StartFragment-->")
    expect(document).toContain("<h2>What makes a high-tensile material</h2>")
    expect(document).not.toContain("mso-style-name")
    expect(document).not.toContain("Version:0.9")
    expect(document.startsWith("<!doctype html>")).toBe(true)
  })

  it("wrapHtmlForWordClipboardPaste emits Word-oriented MSO heading styles", () => {
    const body = "<p class=\"MsoHeading2\" style=\"mso-style-name:'Heading 2';\">What makes a high-tensile material</p>"
    const document = wrapHtmlForWordClipboardPaste(body)

    expect(document).toContain("mso-style-name:\"Heading 2\"")
    expect(document).toContain(".MsoHeading2")
    expect(document).not.toContain("Version:0.9")
  })

  it("renderStructuredNodesToClipboardHtml uses semantic h2 for WordPress and MsoHeading p for Word", () => {
    const nodes: ExportStructuredNode[] = [
      { type: "heading", level: 2, inlineHtml: "What makes a high-tensile material" },
      { type: "heading", level: 3, inlineHtml: "Enhanced Durability" },
    ]
    const wordpress = renderStructuredNodesToClipboardHtml(nodes, "wordpress")
    const word = renderStructuredNodesToClipboardHtml(nodes, "word")

    expect(wordpress).toContain("<h2>What makes a high-tensile material</h2>")
    expect(wordpress).toContain("<h3>Enhanced Durability</h3>")
    expect(wordpress).not.toContain("MsoHeading")

    expect(word).toContain('class="MsoHeading2"')
    expect(word).toContain("mso-style-name:'Heading 2'")
    expect(word).toContain('class="MsoHeading3"')
    expect(word).not.toMatch(/<h2[\s>]/i)
  })

  it("buildHtmlWordClipboardPayload keeps headings for Word paste", async () => {
    const { JSDOM } = await import("jsdom")
    const domWindow = new JSDOM("<!doctype html><html><body></body></html>").window
    const previous = {
      DOMParser: (globalThis as { DOMParser?: typeof DOMParser }).DOMParser,
      document: (globalThis as { document?: Document }).document,
      Node: (globalThis as { Node?: typeof Node }).Node,
    }
    ;(globalThis as unknown as { DOMParser: typeof domWindow.DOMParser }).DOMParser = domWindow.DOMParser
    ;(globalThis as unknown as { document: Document }).document = domWindow.document as unknown as Document
    ;(globalThis as unknown as { Node: typeof domWindow.Node }).Node = domWindow.Node

    try {
      const payload = buildHtmlWordClipboardPayload({
        html: "<h2>Market timing</h2><p>Stay invested.</p>",
        plainText: "Market timing\n\nStay invested.",
      })

      expect(payload).not.toBeNull()
      expect(payload?.htmlBody).toContain('class="MsoHeading2"')
      expect(payload?.htmlBody).toContain("Market timing")
      expect(payload?.htmlDocument).toContain("mso-style-name:\"Heading 2\"")
      expect(payload?.rtfDocument).toContain("heading 2")
      expect(payload?.plainText).toContain("Stay invested.")
    } finally {
      if (previous.DOMParser) {
        ;(globalThis as unknown as { DOMParser: typeof DOMParser }).DOMParser = previous.DOMParser
      } else {
        delete (globalThis as { DOMParser?: typeof DOMParser }).DOMParser
      }
      if (previous.document) {
        ;(globalThis as unknown as { document: Document }).document = previous.document
      }
      if (previous.Node) {
        ;(globalThis as unknown as { Node: typeof Node }).Node = previous.Node
      }
    }
  })

  it("cleanClipboardHtml removes trailing br tags inside headings", () => {
    const cleaned = cleanClipboardHtml("<h2>Benefits of high tensile materials<br></h2><p>Body</p><p></p>")
    expect(cleaned).toContain("<h2>Benefits of high tensile materials</h2>")
    expect(cleaned).not.toMatch(/<h2>[\s\S]*<br[\s/>]/i)
    expect(cleaned).not.toContain("<p></p>")
  })

  it("hydrates stale content_json from content_text when blocks lack semantic headings", () => {
    const normalized = buildNormalizedExportFromLiveOutput({
      component: {
        task_component_id: "tc-materials",
        briefing_component_id: 20,
        title: "O que é?",
        selected: true,
        position: 0,
      },
      output: {
        content_json: [
          { type: "paragraph", text: "What makes a high-tensile material" },
          { type: "paragraph", text: "High tensile materials are substances specifically engineered for strength." },
          { type: "paragraph", text: "Benefits of high tensile materials" },
          { type: "paragraph", text: "High-tensile materials offer a range of advantages." },
          { type: "paragraph", text: "Enhanced Durability" },
          { type: "paragraph", text: "One of the most significant advantages is durability." },
          { type: "paragraph", text: "Limitations of High-Tensile Materials" },
          { type: "paragraph", text: "Every material has trade-offs." },
        ],
        content_text: [
          "<h2>What makes a high-tensile material</h2>",
          "<p>High tensile materials are substances specifically engineered for strength.</p>",
          "<h2>Benefits of high tensile materials</h2>",
          "<p>High-tensile materials offer a range of advantages.</p>",
          "<h3>Enhanced Durability</h3>",
          "<p>One of the most significant advantages is durability.</p>",
          "<h2>Limitations of High-Tensile Materials</h2>",
          "<p>Every material has trade-offs.</p>",
        ].join(""),
        attachments: [],
        attachment_map: null,
      },
    })

    expect(normalized?.docxHtml).toContain("<h2>What makes a high-tensile material</h2>")
    expect(normalized?.clipboardHtml).toContain("<h2>What makes a high-tensile material</h2>")
    expect(normalized?.clipboardHtml).toContain("<h2>Benefits of high tensile materials</h2>")
    expect(normalized?.clipboardHtml).toContain("<h3>Enhanced Durability</h3>")
    expect(normalized?.clipboardHtml).toContain("<h2>Limitations of High-Tensile Materials</h2>")
    expect(normalized?.clipboardHtml).not.toMatch(/<p[^>]*style=/)
    expect(normalized?.clipboardHtml).not.toContain("O que é?")
  })

  it("preserves inline formatting inside clipboard heading tags", () => {
    const blocks: ExportOutputBlock[] = [
      { type: "paragraph", text: "<h2>What makes a <strong>high-tensile</strong> material</h2><p>Body.</p>" },
    ]
    const output: ExportComponentOutput = { attachments: [], attachment_map: null }
    const html = exportBlocksToClipboardHtml(blocks, output)
    expect(html).toContain("<h2>What makes a <strong>high-tensile</strong> material</h2>")
  })

  it("preserves markdown bullet and numbered lists in shared export HTML", () => {
    const markdown = [
      "## What makes a high-tensile material?",
      "",
      "Intro paragraph with a [link](https://example.com).",
      "",
      "### Key properties",
      "",
      "- High tensile strength",
      "- Resistance to deformation",
      "- Long-term durability",
      "",
      "### Main steps",
      "",
      "1. Choose the right material",
      "2. Check load requirements",
      "3. Validate environmental exposure",
      "",
      "Final paragraph.",
    ].join("\n")

    const blocks: ExportOutputBlock[] = [{ type: "paragraph", text: markdown }]
    const output: ExportComponentOutput = { attachments: [], attachment_map: null }
    const html = exportBlocksToClipboardHtml(blocks, output)

    expect(html).toContain("<h2")
    expect(html).toContain("<h3")
    expect(html).toContain("<ul")
    expect(html).toContain("<ol")
    expect(html).toContain("<li")
    expect(html).toContain('href="https://example.com"')
    expect(html).toContain("Final paragraph")
  })

  it("resolveCurrentComponentForExport prefers focused component over stale active id", () => {
    type Row = { task_component_id: string | null; label: string }
    const components: Row[] = [
      { task_component_id: "tc-intro", label: "Intro" },
      { task_component_id: "tc-vantagens", label: "Vantagens" },
      { task_component_id: "tc-limitacoes", label: "Limitações" },
    ]
    const resolved = resolveCurrentComponentForExport({
      components,
      activeComponentId: "tc-intro",
      focusedCardKey: "tc-vantagens",
      isFocusedSingleOutputMode: true,
      getCardKey: (component) => component.task_component_id ?? component.label,
    })
    expect(resolved?.label).toBe("Vantagens")
  })

  it("resolveCurrentComponentForExport uses active component id in normal mode", () => {
    type Row = { task_component_id: string | null; label: string }
    const components: Row[] = [
      { task_component_id: "tc-intro", label: "Intro" },
      { task_component_id: "tc-limitacoes", label: "Limitações" },
    ]
    const resolved = resolveCurrentComponentForExport({
      components,
      activeComponentId: "tc-limitacoes",
      focusedCardKey: null,
      isFocusedSingleOutputMode: false,
      getCardKey: (component) => component.task_component_id ?? component.label,
    })
    expect(resolved?.label).toBe("Limitações")
  })

  it("resolveCurrentComponentForExport does not fall back to the first component", () => {
    type Row = { task_component_id: string | null; label: string }
    const components: Row[] = [
      { task_component_id: "tc-intro", label: "Intro" },
      { task_component_id: "tc-vantagens", label: "Vantagens" },
    ]
    const resolved = resolveCurrentComponentForExport({
      components,
      activeComponentId: null,
      focusedCardKey: null,
      isFocusedSingleOutputMode: false,
      getCardKey: (component) => component.task_component_id ?? component.label,
    })
    expect(resolved).toBeNull()
  })

  it("renderComponentsToClipboardHtml joins multiple components without internal labels", () => {
    const components = [
      {
        id: "bc:1",
        title: "Intro",
        type: null,
        contentHtml: "<h2>Real intro heading</h2><p>Intro body.</p>",
        contentText: "Intro body.",
        contentJson: [],
        docxHtml: "<h2>Real intro heading</h2><p>Intro body.</p>",
        clipboardHtml: "<h2>Real intro heading</h2><p>Intro body.</p>",
        hasContent: true,
        assets: [],
      },
      {
        id: "bc:2",
        title: "O que é?",
        type: null,
        contentHtml: "<p>Vantagens detail.</p>",
        contentText: "Vantagens detail.",
        contentJson: [],
        docxHtml: "<p>Vantagens detail.</p>",
        clipboardHtml: "<p>Vantagens detail.</p>",
        hasContent: true,
        assets: [],
      },
    ]
    const html = renderComponentsToClipboardHtml(components)
    expect(html).toContain("Real intro heading")
    expect(html).toContain("Vantagens detail.")
    expect(html).not.toContain("O que é?")
    expect(html).not.toContain("Intro</h2>")
    // Components are joined with clean spacing, never empty <p></p> wrappers that
    // would break heading structure when pasted into Word / WordPress.
    expect(html).not.toContain("<p></p>")
    expect(html).toContain("<h2>Real intro heading</h2><p>Intro body.</p>")
  })

  it("preserves h1-h3 heading levels in clipboard HTML using the same export body as DOCX", () => {
    const markdown = [
      "# Main title",
      "## Section title",
      "### Subsection title",
      "Body paragraph.",
    ].join("\n\n")
    const normalized = buildNormalizedExportFromLiveOutput({
      component: {
        task_component_id: "tc-headings",
        briefing_component_id: 1,
        title: "Intro",
        selected: true,
        position: 0,
      },
      output: {
        content_json: [{ type: "paragraph", text: markdown }],
        attachments: [],
        attachment_map: null,
      },
    })

    expect(normalized?.docxHtml).toContain("<h1")
    expect(normalized?.docxHtml).toContain("<h2")
    expect(normalized?.docxHtml).toContain("<h3")
    expect(renderComponentToClipboardHtml(normalized!)).toContain("<h1")
    expect(renderComponentToClipboardHtml(normalized!)).toContain("<h2")
    expect(renderComponentToClipboardHtml(normalized!)).toContain("<h3")
    expect(renderComponentToClipboardHtml({
      title: "Intro",
      docxHtml: "<h1>Main title</h1><h2>Section title</h2><h3>Subsection title</h3><p>Body paragraph.</p>",
    })).toContain("<h2>Section title</h2>")
  })
})
