export type ContentChangeSourceBadge = "ai" | "manual" | "rollback"

export type TaskComponentOutputVersion = {
  id: string
  task_component_output_id: string
  task_id: number
  channel_id: number
  task_component_id: string | null
  briefing_component_id: number | null
  version_number: number
  content_text: string | null
  content_json: unknown | null
  output_kind: string | null
  is_autogenerated: boolean | null
  change_source: string
  changed_by: number | null
  changed_by_name: string | null
  ai_message_id: string | null
  ai_thread_id: string | null
  change_summary: string | null
  created_at: string
}

export type TaskChannelContentVersion = {
  id: string
  task_id: number
  channel_id: number
  version_number: number
  snapshot: unknown
  change_source: string
  changed_by: number | null
  changed_by_name: string | null
  ai_message_id: string | null
  ai_thread_id: string | null
  change_summary: string | null
  created_at: string
}

export type RolledBackTaskComponentOutput = {
  id: string
  content_text: string | null
  content_json: unknown | null
  output_kind: string | null
  is_autogenerated: boolean | null
  updated_at: string | null
}
