import type { TaskComponentOutputAttachment } from "@/lib/types/task-component-output"
/**
 * Response from the `task-channel-bootstrap` edge function.
 * Replaces per-channel RPC/view reads for briefing row, SEO, composed output, and component lists.
 */

export type TaskChannelBootstrapChannel = {
  id: number
  name: string | null
}

export type TaskChannelBootstrapBriefing = {
  briefing_type_id: number | null
  disable_briefing: boolean
}

export type TaskChannelBootstrapSeo = {
  effective: {
    seo_required: boolean | null
    seo_source: string | null
  } | null
  override: {
    primary_keyword: string | null
    secondary_keywords: string[] | string | null
    seo_required_override: boolean | null
  } | null
}

export type TaskChannelBootstrapComposedOutputRow = {
  task_component_id: string | null
  briefing_component_id: number | null
  task_component_output_id: string | null
  title: string | null
  description: string | null
  content_text: string | null
  content: unknown
  resolved_content_json: unknown
  content_json: unknown
  attachment_map: Record<string, TaskComponentOutputAttachment> | null
  attachments: TaskComponentOutputAttachment[]
  position: number | null
  updated_at: string | null
  is_autogenerated: boolean | null
  comment_thread_count: number
  open_comment_thread_count: number
}

export type TaskChannelBootstrapComponentRow = {
  task_component_id: string | null
  briefing_component_id: number | null
  title: string | null
  description: string | null
  selected: boolean
  position: number | null
  template_layer: string | null
  is_ad_hoc: boolean
  origin: string | null
  global_overridden: boolean
  template_title: string | null
  template_description: string | null
  project_template_title: string | null
  project_template_description: string | null
  component_key: string | null
  kind: string | null
}

export type TaskChannelBootstrapAvailableRow = {
  task_component_id: string | null
  component_key: string
  kind: string
  key: string
  component_id: number | null
  is_project_component: boolean
  title: string
  description: string | null
  custom_title: string | null
  custom_description: string | null
  tag: string
  template_layer: string | null
  position: number | null
  origin: string | null
  global_overridden: boolean
  in_current_template: boolean
}

export type TaskChannelBootstrapResponse = {
  task_id: number
  channel_id: number
  channel: TaskChannelBootstrapChannel | null
  /** Replaces per-channel `task_channel_briefings` read on initial load. */
  briefing: TaskChannelBootstrapBriefing | null
  seo: TaskChannelBootstrapSeo | null
  composed_output: TaskChannelBootstrapComposedOutputRow[]
  components: TaskChannelBootstrapComponentRow[]
  available_components: TaskChannelBootstrapAvailableRow[]
  meta: {
    bootstrap_version: number
    fetched_at: string
  }
}
