/**
 * Response from `public.get_task_channel_content_v1`.
 * Briefing type is legacy metadata and must not gate which components are visible.
 */

export type TaskChannelContentComponentRow = {
  task_component_id: string | null
  briefing_component_id: number | null
  title: string | null
  description: string | null
  selected: boolean
  position: number | null
  template_layer: string | null
  is_ad_hoc: boolean
  origin: string | null
  global_overridden: boolean
  template_title: string | null
  template_description: string | null
  project_template_title: string | null
  project_template_description: string | null
  component_key: string | null
  kind: string | null
  [key: string]: unknown
}

export type TaskChannelContentOutputRow = {
  task_component_id: string | null
  briefing_component_id: number | null
  task_component_output_id?: string | null
  id?: string | null
  title: string | null
  description: string | null
  content_text: string | null
  content: unknown
  resolved_content_json?: unknown
  content_json: unknown
  attachment_map?: Record<string, unknown> | null
  attachments?: unknown[]
  position: number | null
  updated_at: string | null
  is_autogenerated?: boolean | null
  comment_thread_count?: number
  open_comment_thread_count?: number
  [key: string]: unknown
}

export type TaskChannelContentRecoverableOutput = {
  id: string
  task_id?: number | null
  channel_id?: number | null
  task_component_id?: string | null
  briefing_component_id?: number | null
  title?: string | null
  content_text?: string | null
  updated_at?: string | null
  [key: string]: unknown
}

export type TaskChannelContentResponse = {
  ok: true
  context_version: 1
  briefing_type_used: false
  task_id: number
  project_id: number
  channel_id: number
  channel: Record<string, unknown>
  components: TaskChannelContentComponentRow[]
  composed_output: TaskChannelContentOutputRow[]
  latest_outputs: TaskChannelContentOutputRow[]
  recoverable_outputs: TaskChannelContentRecoverableOutput[]
  fallback_main_required: boolean
}
