"use client"

import { createClientComponentClient } from "@supabase/auth-helpers-nextjs"
import { useQuery } from "@tanstack/react-query"
import {
  normalizeTaskComponentOutputAttachments,
  type TaskComponentOutputAttachment,
} from "@/lib/types/task-component-output"

export interface TaskChannelComposedOutputRow {
  task_component_id: string | null
  briefing_component_id: number | null
  task_component_output_id: string | null
  title: string | null
  description: string | null
  content_text: string | null
  content: unknown
  resolved_content_json: unknown
  content_json: unknown
  attachment_map: Record<string, TaskComponentOutputAttachment> | null
  attachments: TaskComponentOutputAttachment[]
  position: number | null
  updated_at: string | null
  is_autogenerated: boolean | null
  comment_thread_count: number | null
  open_comment_thread_count: number | null
}

export function useTaskChannelComposedOutput(
  taskId?: number | null,
  channelId?: number | null,
  options?: { enabled?: boolean }
) {
  const supabase = createClientComponentClient()
  const enabled = (options?.enabled ?? true) && !!taskId && !!channelId

  return useQuery({
    queryKey: ["task-channel-composed-output", taskId ?? null, channelId ?? null],
    enabled,
    queryFn: async (): Promise<TaskChannelComposedOutputRow[]> => {
      if (!taskId || !channelId) return []
      const { data, error } = await supabase.rpc("task_channel_composed_output", {
        p_task_id: taskId,
        p_channel_id: channelId,
      })
      if (error) throw error
      return ((data ?? []) as any[]).map((row) => ({
        task_component_id: typeof row.task_component_id === "string" ? row.task_component_id : null,
        briefing_component_id: typeof row.briefing_component_id === "number" ? row.briefing_component_id : null,
        task_component_output_id: typeof row.task_component_output_id === "string" ? row.task_component_output_id : null,
        title: typeof row.title === "string" ? row.title : null,
        description: typeof row.description === "string" ? row.description : null,
        content_text: typeof row.content_text === "string" ? row.content_text : null,
        content: row.content ?? null,
        resolved_content_json: row.resolved_content_json ?? null,
        content_json: row.content_json ?? null,
        attachment_map:
          row.attachment_map && typeof row.attachment_map === "object"
            ? (row.attachment_map as Record<string, TaskComponentOutputAttachment>)
            : null,
        attachments: normalizeTaskComponentOutputAttachments(row.attachments),
        position: typeof row.position === "number" ? row.position : null,
        updated_at: typeof row.updated_at === "string" ? row.updated_at : null,
        is_autogenerated: typeof row.is_autogenerated === "boolean" ? row.is_autogenerated : null,
        comment_thread_count: Number.isFinite(Number(row.comment_thread_count))
          ? Number(row.comment_thread_count)
          : 0,
        open_comment_thread_count: Number.isFinite(Number(row.open_comment_thread_count))
          ? Number(row.open_comment_thread_count)
          : 0,
      }))
    },
    staleTime: 30_000,
  })
}
