import { getSupabaseBrowser } from "../../../lib/supabase-browser"
import type {
  ContentChangeSourceBadge,
  RolledBackTaskComponentOutput,
  TaskChannelContentVersion,
  TaskComponentOutputVersion,
} from "@/lib/types/content-version-history"

const COMPONENT_VERSION_SELECT =
  "id, task_component_output_id, task_id, channel_id, task_component_id, briefing_component_id, version_number, content_text, content_json, output_kind, is_autogenerated, change_source, changed_by, ai_message_id, ai_thread_id, change_summary, created_at, changed_by_user:users!task_component_output_versions_changed_by_fkey(full_name)"

const CHANNEL_VERSION_SELECT =
  "id, task_id, channel_id, version_number, snapshot, change_source, changed_by, ai_message_id, ai_thread_id, change_summary, created_at"

function normalizeComponentVersionRow(row: Record<string, unknown>): TaskComponentOutputVersion {
  const changedByUser = row.changed_by_user
  const changedByName =
    changedByUser && typeof changedByUser === "object" && typeof (changedByUser as { full_name?: unknown }).full_name === "string"
      ? ((changedByUser as { full_name: string }).full_name ?? null)
      : null

  return {
    id: String(row.id),
    task_component_output_id: String(row.task_component_output_id),
    task_id: Number(row.task_id),
    channel_id: Number(row.channel_id),
    task_component_id: row.task_component_id != null ? String(row.task_component_id) : null,
    briefing_component_id:
      typeof row.briefing_component_id === "number" ? row.briefing_component_id : null,
    version_number: Number(row.version_number),
    content_text: typeof row.content_text === "string" ? row.content_text : null,
    content_json: row.content_json ?? null,
    output_kind: typeof row.output_kind === "string" ? row.output_kind : null,
    is_autogenerated: typeof row.is_autogenerated === "boolean" ? row.is_autogenerated : null,
    change_source: String(row.change_source ?? "manual"),
    changed_by: typeof row.changed_by === "number" ? row.changed_by : null,
    changed_by_name: changedByName,
    ai_message_id: typeof row.ai_message_id === "string" ? row.ai_message_id : null,
    ai_thread_id: typeof row.ai_thread_id === "string" ? row.ai_thread_id : null,
    change_summary: typeof row.change_summary === "string" ? row.change_summary : null,
    created_at: String(row.created_at),
  }
}

function normalizeChannelVersionRow(row: Record<string, unknown>): TaskChannelContentVersion {
  return {
    id: String(row.id),
    task_id: Number(row.task_id),
    channel_id: Number(row.channel_id),
    version_number: Number(row.version_number),
    snapshot: row.snapshot ?? null,
    change_source: String(row.change_source ?? "manual"),
    changed_by: typeof row.changed_by === "number" ? row.changed_by : null,
    changed_by_name: null,
    ai_message_id: typeof row.ai_message_id === "string" ? row.ai_message_id : null,
    ai_thread_id: typeof row.ai_thread_id === "string" ? row.ai_thread_id : null,
    change_summary: typeof row.change_summary === "string" ? row.change_summary : null,
    created_at: String(row.created_at),
  }
}

export function resolveChangeSourceBadge(changeSource: string): {
  label: string
  badge: ContentChangeSourceBadge
} {
  const normalized = changeSource.trim().toLowerCase()
  if (normalized === "rollback" || normalized.includes("rollback")) {
    return { label: "Rollback", badge: "rollback" }
  }
  if (normalized === "manual" || normalized === "user") {
    return { label: "Manual", badge: "manual" }
  }
  if (normalized.startsWith("ai") || normalized === "autogenerated") {
    return { label: "AI", badge: "ai" }
  }
  return { label: changeSource, badge: "manual" }
}

export async function fetchTaskComponentOutputVersions(
  taskComponentOutputId: string,
): Promise<TaskComponentOutputVersion[]> {
  const supabase = getSupabaseBrowser()
  const { data, error } = await supabase
    .from("task_component_output_versions")
    .select(COMPONENT_VERSION_SELECT)
    .eq("task_component_output_id", taskComponentOutputId)
    .order("version_number", { ascending: false })

  if (error) throw error
  return (data ?? []).map((row) => normalizeComponentVersionRow(row as Record<string, unknown>))
}

/** All component-output versions for a task × channel, newest first. */
export async function fetchTaskChannelComponentOutputVersions(
  taskId: number,
  channelId: number,
): Promise<TaskComponentOutputVersion[]> {
  const supabase = getSupabaseBrowser()
  const { data, error } = await supabase
    .from("task_component_output_versions")
    .select(COMPONENT_VERSION_SELECT)
    .eq("task_id", taskId)
    .eq("channel_id", channelId)
    .order("created_at", { ascending: false })

  if (error) throw error
  return (data ?? []).map((row) => normalizeComponentVersionRow(row as Record<string, unknown>))
}

export async function fetchTaskChannelContentVersions(
  taskId: number,
  channelId: number,
): Promise<TaskChannelContentVersion[]> {
  const supabase = getSupabaseBrowser()
  const { data, error } = await supabase
    .from("task_channel_content_versions")
    .select(CHANNEL_VERSION_SELECT)
    .eq("task_id", taskId)
    .eq("channel_id", channelId)
    .order("version_number", { ascending: false })

  if (error) throw error
  return (data ?? []).map((row) => normalizeChannelVersionRow(row as Record<string, unknown>))
}

export async function rollbackTaskComponentOutputVersion(args: {
  taskComponentOutputId: string
  versionNumber: number
}): Promise<RolledBackTaskComponentOutput> {
  const supabase = getSupabaseBrowser()
  const { data, error } = await supabase.rpc("rollback_task_component_output_version", {
    p_task_component_output_id: args.taskComponentOutputId,
    p_version_number: args.versionNumber,
  })
  if (error) throw error
  const row = (data ?? {}) as Record<string, unknown>
  return {
    id: String(row.id),
    content_text: typeof row.content_text === "string" ? row.content_text : null,
    content_json: row.content_json ?? null,
    output_kind: typeof row.output_kind === "string" ? row.output_kind : null,
    is_autogenerated: typeof row.is_autogenerated === "boolean" ? row.is_autogenerated : null,
    updated_at: typeof row.updated_at === "string" ? row.updated_at : null,
  }
}

export async function rollbackTaskChannelContentVersion(versionId: string): Promise<unknown> {
  const supabase = getSupabaseBrowser()
  const { data, error } = await supabase.rpc("rollback_task_channel_content_version", {
    p_version_id: versionId,
  })
  if (error) throw error
  return data
}

export async function saveTaskChannelContentVersion(args: {
  taskId: number
  channelId: number
  changeSource?: string
  changeSummary?: string | null
  aiMessageId?: string | null
  aiThreadId?: string | null
}): Promise<void> {
  const supabase = getSupabaseBrowser()
  const { error } = await supabase.rpc("save_task_channel_content_version", {
    p_task_id: args.taskId,
    p_channel_id: args.channelId,
    p_change_source: args.changeSource ?? "ai_before_edit",
    p_change_summary: args.changeSummary ?? null,
    p_ai_message_id: args.aiMessageId ?? null,
    p_ai_thread_id: args.aiThreadId ?? null,
  })
  if (error) throw error
}
