-- Google Search Console overview: daily aggregates, sync runs, sitemaps,
-- URL Inspection snapshots, brand terms, and project RPCs.

-- ---------------------------------------------------------------------------
-- 1) Alter existing GSC property + page/query daily metadata
-- ---------------------------------------------------------------------------

alter table public.project_search_console_properties
  add column if not exists earliest_metric_date date null,
  add column if not exists latest_metric_date date null,
  add column if not exists backfill_status text null,
  add column if not exists backfill_progress jsonb not null default '{}'::jsonb;

alter table public.project_search_console_properties
  drop constraint if exists project_search_console_properties_backfill_status_check;

alter table public.project_search_console_properties
  add constraint project_search_console_properties_backfill_status_check check (
    backfill_status is null
    or backfill_status in (
      'queued', 'running', 'partial', 'completed', 'failed', 'cancelled'
    )
  );

alter table public.project_search_console_page_query_daily
  add column if not exists search_type text not null default 'web',
  add column if not exists aggregation_type text not null default 'auto',
  add column if not exists site_page_id bigint null,
  add column if not exists is_partial boolean not null default false;

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public' and table_name = 'project_site_pages'
  ) then
    begin
      alter table public.project_search_console_page_query_daily
        add constraint project_search_console_page_query_daily_site_page_fk
        foreign key (site_page_id) references public.project_site_pages(id)
        on delete set null;
    exception
      when duplicate_object then null;
    end;
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 2) Sync runs
-- ---------------------------------------------------------------------------

create table if not exists public.project_search_console_sync_runs (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  property_id bigint null
    references public.project_search_console_properties(id) on delete set null,
  job_type text not null,
  status text not null default 'queued',
  run_trigger text not null default 'manual',
  requested_date_from date null,
  requested_date_to date null,
  completed_date_from date null,
  completed_date_to date null,
  search_type text not null default 'web',
  rows_received integer not null default 0,
  rows_inserted integer not null default 0,
  rows_updated integer not null default 0,
  quota_errors integer not null default 0,
  is_partial boolean not null default false,
  error_message text null,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz null,
  finished_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_search_console_sync_runs_job_type_check check (
    job_type in (
      'performance',
      'backfill',
      'sitemaps',
      'url_inspection',
      'properties'
    )
  ),
  constraint project_search_console_sync_runs_status_check check (
    status in (
      'queued', 'running', 'partial', 'completed', 'failed', 'cancelled'
    )
  ),
  constraint project_search_console_sync_runs_trigger_check check (
    run_trigger in ('manual', 'automatic', 'oauth_connect')
  )
);

create index if not exists idx_gsc_sync_runs_project_created
  on public.project_search_console_sync_runs (project_id, created_at desc);

create index if not exists idx_gsc_sync_runs_property_status
  on public.project_search_console_sync_runs (property_id, status)
  where property_id is not null;

-- ---------------------------------------------------------------------------
-- 3) Property / query / page daily metrics
-- ---------------------------------------------------------------------------

create table if not exists public.project_search_console_property_daily (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  property_id bigint not null
    references public.project_search_console_properties(id) on delete cascade,
  metric_date date not null,
  search_type text not null default 'web',
  aggregation_type text not null default 'auto',
  country text not null default '',
  device text not null default '',
  clicks integer null,
  impressions integer null,
  ctr numeric null,
  position numeric null,
  query_count integer null,
  page_count integer null,
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_search_console_property_daily_unique unique (
    property_id, metric_date, search_type, country, device, aggregation_type
  )
);

create index if not exists idx_gsc_property_daily_project_date
  on public.project_search_console_property_daily (project_id, metric_date desc);

create table if not exists public.project_search_console_query_daily (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  property_id bigint not null
    references public.project_search_console_properties(id) on delete cascade,
  metric_date date not null,
  query text not null,
  search_type text not null default 'web',
  aggregation_type text not null default 'auto',
  country text not null default '',
  device text not null default '',
  clicks integer null,
  impressions integer null,
  ctr numeric null,
  position numeric null,
  page_count integer null,
  first_seen_at date null,
  last_seen_at date null,
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_search_console_query_daily_unique unique (
    property_id, metric_date, query, search_type, country, device, aggregation_type
  )
);

create index if not exists idx_gsc_query_daily_project_date
  on public.project_search_console_query_daily (project_id, metric_date desc);

create index if not exists idx_gsc_query_daily_query
  on public.project_search_console_query_daily (project_id, query);

create table if not exists public.project_search_console_page_daily (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  property_id bigint not null
    references public.project_search_console_properties(id) on delete cascade,
  site_page_id bigint null,
  metric_date date not null,
  page_url text not null,
  canonical_url text null,
  search_type text not null default 'web',
  aggregation_type text not null default 'auto',
  country text not null default '',
  device text not null default '',
  clicks integer null,
  impressions integer null,
  ctr numeric null,
  position numeric null,
  query_count integer null,
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_search_console_page_daily_unique unique (
    property_id, metric_date, page_url, search_type, country, device, aggregation_type
  )
);

create index if not exists idx_gsc_page_daily_project_date
  on public.project_search_console_page_daily (project_id, metric_date desc);

create index if not exists idx_gsc_page_daily_canonical
  on public.project_search_console_page_daily (project_id, canonical_url)
  where canonical_url is not null;

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public' and table_name = 'project_site_pages'
  ) then
    begin
      alter table public.project_search_console_page_daily
        add constraint project_search_console_page_daily_site_page_fk
        foreign key (site_page_id) references public.project_site_pages(id)
        on delete set null;
    exception
      when duplicate_object then null;
    end;
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 4) Sitemaps
-- ---------------------------------------------------------------------------

create table if not exists public.project_search_console_sitemaps (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  property_id bigint not null
    references public.project_search_console_properties(id) on delete cascade,
  path text not null,
  sitemap_type text null,
  is_pending boolean not null default false,
  is_sitemap_index boolean not null default false,
  last_submitted_at timestamptz null,
  last_downloaded_at timestamptz null,
  submitted_urls_count integer null,
  warnings_count integer null,
  errors_count integer null,
  contents jsonb not null default '[]'::jsonb,
  raw_payload jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_search_console_sitemaps_unique unique (property_id, path)
);

create index if not exists idx_gsc_sitemaps_project
  on public.project_search_console_sitemaps (project_id, last_seen_at desc);

-- ---------------------------------------------------------------------------
-- 5) URL Inspection snapshots + queue
-- ---------------------------------------------------------------------------

create table if not exists public.project_site_page_index_snapshots (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  site_page_id bigint null,
  property_id bigint null
    references public.project_search_console_properties(id) on delete set null,
  inspected_url text not null,
  inspection_date timestamptz not null default now(),
  inspection_status text not null default 'succeeded',
  verdict text null,
  coverage_state text null,
  robots_txt_state text null,
  indexing_state text null,
  page_fetch_state text null,
  last_crawl_time timestamptz null,
  google_canonical text null,
  user_canonical text null,
  crawled_as text null,
  sitemap_urls jsonb not null default '[]'::jsonb,
  referring_urls jsonb not null default '[]'::jsonb,
  inspection_result_link text null,
  rich_results_status text null,
  rich_results_items jsonb not null default '[]'::jsonb,
  issues jsonb not null default '[]'::jsonb,
  internal_issue_category text null,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint project_site_page_index_snapshots_status_check check (
    inspection_status in ('queued', 'running', 'succeeded', 'failed', 'skipped')
  ),
  constraint project_site_page_index_snapshots_category_check check (
    internal_issue_category is null
    or internal_issue_category in (
      'not_indexed',
      'blocked_by_robots',
      'blocked_by_noindex',
      'fetch_error',
      'server_error',
      'soft_404',
      'redirect',
      'duplicate',
      'canonical_mismatch',
      'discovered_not_indexed',
      'crawled_not_indexed',
      'rich_result_issue',
      'unknown',
      'indexed'
    )
  )
);

create index if not exists idx_site_page_index_snapshots_project_date
  on public.project_site_page_index_snapshots (project_id, inspection_date desc);

create index if not exists idx_site_page_index_snapshots_page
  on public.project_site_page_index_snapshots (site_page_id, inspection_date desc)
  where site_page_id is not null;

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'public' and table_name = 'project_site_pages'
  ) then
    begin
      alter table public.project_site_page_index_snapshots
        add constraint project_site_page_index_snapshots_site_page_fk
        foreign key (site_page_id) references public.project_site_pages(id)
        on delete set null;
    exception
      when duplicate_object then null;
    end;
  end if;
end $$;

create table if not exists public.project_search_console_inspect_queue (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  property_id bigint not null
    references public.project_search_console_properties(id) on delete cascade,
  site_page_id bigint null,
  url text not null,
  priority integer not null default 100,
  status text not null default 'queued',
  attempts integer not null default 0,
  last_error text null,
  requested_by_auth_user_id uuid null,
  scheduled_for timestamptz not null default now(),
  started_at timestamptz null,
  finished_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_search_console_inspect_queue_status_check check (
    status in ('queued', 'running', 'completed', 'failed', 'cancelled')
  )
);

create unique index if not exists project_search_console_inspect_queue_active_unique
  on public.project_search_console_inspect_queue (property_id, url)
  where status in ('queued', 'running');

create index if not exists idx_gsc_inspect_queue_due
  on public.project_search_console_inspect_queue (status, scheduled_for, priority);

-- ---------------------------------------------------------------------------
-- 6) Brand terms for branded / non-branded segmentation
-- ---------------------------------------------------------------------------

create table if not exists public.project_search_brand_terms (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  term text not null,
  term_type text not null default 'variant',
  is_exclusion boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_search_brand_terms_type_check check (
    term_type in (
      'primary', 'variant', 'abbreviation', 'product', 'domain', 'other'
    )
  ),
  constraint project_search_brand_terms_unique unique (project_id, term, is_exclusion)
);

create index if not exists idx_project_search_brand_terms_project
  on public.project_search_brand_terms (project_id);

-- ---------------------------------------------------------------------------
-- 7) RLS
-- ---------------------------------------------------------------------------

alter table public.project_search_console_sync_runs enable row level security;
alter table public.project_search_console_property_daily enable row level security;
alter table public.project_search_console_query_daily enable row level security;
alter table public.project_search_console_page_daily enable row level security;
alter table public.project_search_console_sitemaps enable row level security;
alter table public.project_site_page_index_snapshots enable row level security;
alter table public.project_search_console_inspect_queue enable row level security;
alter table public.project_search_brand_terms enable row level security;

drop policy if exists project_search_console_sync_runs_select
  on public.project_search_console_sync_runs;
create policy project_search_console_sync_runs_select
  on public.project_search_console_sync_runs for select to authenticated
  using (public.can_edit_project(project_id));

drop policy if exists project_search_console_property_daily_select
  on public.project_search_console_property_daily;
create policy project_search_console_property_daily_select
  on public.project_search_console_property_daily for select to authenticated
  using (public.can_edit_project(project_id));

drop policy if exists project_search_console_query_daily_select
  on public.project_search_console_query_daily;
create policy project_search_console_query_daily_select
  on public.project_search_console_query_daily for select to authenticated
  using (public.can_edit_project(project_id));

drop policy if exists project_search_console_page_daily_select
  on public.project_search_console_page_daily;
create policy project_search_console_page_daily_select
  on public.project_search_console_page_daily for select to authenticated
  using (public.can_edit_project(project_id));

drop policy if exists project_search_console_sitemaps_select
  on public.project_search_console_sitemaps;
create policy project_search_console_sitemaps_select
  on public.project_search_console_sitemaps for select to authenticated
  using (public.can_edit_project(project_id));

drop policy if exists project_site_page_index_snapshots_select
  on public.project_site_page_index_snapshots;
create policy project_site_page_index_snapshots_select
  on public.project_site_page_index_snapshots for select to authenticated
  using (public.can_edit_project(project_id));

drop policy if exists project_search_console_inspect_queue_select
  on public.project_search_console_inspect_queue;
create policy project_search_console_inspect_queue_select
  on public.project_search_console_inspect_queue for select to authenticated
  using (public.can_edit_project(project_id));

drop policy if exists project_search_brand_terms_all
  on public.project_search_brand_terms;
create policy project_search_brand_terms_select
  on public.project_search_brand_terms for select to authenticated
  using (public.can_edit_project(project_id));
create policy project_search_brand_terms_insert
  on public.project_search_brand_terms for insert to authenticated
  with check (public.can_edit_project(project_id));
create policy project_search_brand_terms_update
  on public.project_search_brand_terms for update to authenticated
  using (public.can_edit_project(project_id))
  with check (public.can_edit_project(project_id));
create policy project_search_brand_terms_delete
  on public.project_search_brand_terms for delete to authenticated
  using (public.can_edit_project(project_id));

revoke insert, update, delete on public.project_search_console_sync_runs from authenticated;
revoke insert, update, delete on public.project_search_console_property_daily from authenticated;
revoke insert, update, delete on public.project_search_console_query_daily from authenticated;
revoke insert, update, delete on public.project_search_console_page_daily from authenticated;
revoke insert, update, delete on public.project_search_console_sitemaps from authenticated;
revoke insert, update, delete on public.project_site_page_index_snapshots from authenticated;
revoke insert, update, delete on public.project_search_console_inspect_queue from authenticated;

grant select on public.project_search_console_sync_runs to authenticated;
grant select on public.project_search_console_property_daily to authenticated;
grant select on public.project_search_console_query_daily to authenticated;
grant select on public.project_search_console_page_daily to authenticated;
grant select on public.project_search_console_sitemaps to authenticated;
grant select on public.project_site_page_index_snapshots to authenticated;
grant select on public.project_search_console_inspect_queue to authenticated;
grant select, insert, update, delete on public.project_search_brand_terms to authenticated;

grant all on public.project_search_console_sync_runs to service_role;
grant all on public.project_search_console_property_daily to service_role;
grant all on public.project_search_console_query_daily to service_role;
grant all on public.project_search_console_page_daily to service_role;
grant all on public.project_search_console_sitemaps to service_role;
grant all on public.project_site_page_index_snapshots to service_role;
grant all on public.project_search_console_inspect_queue to service_role;
grant all on public.project_search_brand_terms to service_role;

-- ---------------------------------------------------------------------------
-- 8) Helpers
-- ---------------------------------------------------------------------------

create or replace function public.fn_gsc_metric_bundle(
  p_clicks numeric,
  p_impressions numeric,
  p_position_weighted numeric
)
returns jsonb
language sql
immutable
as $$
  select jsonb_build_object(
    'clicks', coalesce(p_clicks, 0),
    'impressions', coalesce(p_impressions, 0),
    'ctr', case
      when coalesce(p_impressions, 0) <= 0 then null
      else p_clicks / nullif(p_impressions, 0)
    end,
    'position_avg', case
      when coalesce(p_impressions, 0) <= 0 then null
      else p_position_weighted / nullif(p_impressions, 0)
    end
  );
$$;

-- ---------------------------------------------------------------------------
-- 9) Integrations status (GA + GSC separately)
-- ---------------------------------------------------------------------------

create or replace function public.fn_get_project_google_integrations_status(
  p_project_id integer
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_oauth jsonb;
  v_ga jsonb;
  v_gsc jsonb;
begin
  if p_project_id is null or not public.can_edit_project(p_project_id) then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  v_oauth := public.fn_get_project_google_oauth_status(p_project_id);

  begin
    select coalesce(
      (
        select jsonb_build_object(
          'connected', true,
          'ga_property_id', p.ga_property_id,
          'default_uri', p.default_uri,
          'updated_at', p.updated_at
        )
        from public.project_analytics_properties p
        where p.project_id = p_project_id
          and p.is_active = true
        order by p.updated_at desc
        limit 1
      ),
      jsonb_build_object('connected', false)
    )
    into v_ga;
  exception
    when undefined_table then
      v_ga := jsonb_build_object('connected', false);
  end;

  select coalesce(
    (
      select jsonb_build_object(
        'connected', true,
        'id', p.id,
        'property_url', p.property_url,
        'site_type', p.site_type,
        'last_synced_at', p.last_synced_at,
        'last_sync_status', p.last_sync_status,
        'last_sync_error', p.last_sync_error,
        'earliest_metric_date', p.earliest_metric_date,
        'latest_metric_date', p.latest_metric_date,
        'backfill_status', p.backfill_status,
        'backfill_progress', p.backfill_progress
      )
      from public.project_search_console_properties p
      where p.project_id = p_project_id
        and p.is_active = true
      order by p.updated_at desc
      limit 1
    ),
    jsonb_build_object('connected', false)
  )
  into v_gsc;

  return jsonb_build_object(
    'project_id', p_project_id,
    'oauth', v_oauth,
    'analytics', v_ga,
    'search_console', v_gsc
  );
end;
$$;

revoke all on function public.fn_get_project_google_integrations_status(integer) from public;
grant execute on function public.fn_get_project_google_integrations_status(integer) to authenticated;
grant execute on function public.fn_get_project_google_integrations_status(integer) to service_role;

-- ---------------------------------------------------------------------------
-- 10) Overview RPC
-- ---------------------------------------------------------------------------

create or replace function public.fn_get_project_search_overview(
  p_project_id integer,
  p_date_from date default null,
  p_date_to date default null,
  p_compare_date_from date default null,
  p_compare_date_to date default null,
  p_search_type text default 'web',
  p_limit integer default 10
)
returns jsonb
language plpgsql
stable
security invoker
set search_path to 'pg_catalog', 'public'
as $$
declare
  v_limit integer := least(greatest(coalesce(p_limit, 10), 1), 50);
  v_search_type text := coalesce(nullif(trim(p_search_type), ''), 'web');
  v_connected boolean;
  v_property jsonb;
  v_current jsonb;
  v_previous jsonb;
  v_timeseries jsonb;
  v_queries jsonb;
  v_pages jsonb;
  v_opportunities jsonb;
  v_indexation jsonb;
  v_has_property_daily boolean;
  v_latest_metric_date date;
  v_last_synced_at timestamptz;
begin
  if p_project_id is null or not public.can_edit_project(p_project_id) then
    raise exception 'forbidden';
  end if;

  select exists (
    select 1
    from public.project_search_console_properties p
    where p.project_id = p_project_id and p.is_active = true
  )
  into v_connected;

  select jsonb_build_object(
    'id', p.id,
    'property_url', p.property_url,
    'site_type', p.site_type,
    'last_synced_at', p.last_synced_at,
    'last_sync_status', p.last_sync_status,
    'last_sync_error', p.last_sync_error,
    'earliest_metric_date', p.earliest_metric_date,
    'latest_metric_date', p.latest_metric_date,
    'backfill_status', p.backfill_status
  ),
  p.last_synced_at,
  p.latest_metric_date
  into v_property, v_last_synced_at, v_latest_metric_date
  from public.project_search_console_properties p
  where p.project_id = p_project_id
    and p.is_active = true
  order by p.updated_at desc
  limit 1;

  select exists (
    select 1
    from public.project_search_console_property_daily d
    where d.project_id = p_project_id
      and d.search_type = v_search_type
      and d.country = ''
      and d.device = ''
      and (p_date_from is null or d.metric_date >= p_date_from)
      and (p_date_to is null or d.metric_date <= p_date_to)
    limit 1
  )
  into v_has_property_daily;

  if v_has_property_daily then
    select public.fn_gsc_metric_bundle(
      sum(d.clicks)::numeric,
      sum(d.impressions)::numeric,
      sum(coalesce(d.position, 0) * coalesce(d.impressions, 0))::numeric
    )
    into v_current
    from public.project_search_console_property_daily d
    where d.project_id = p_project_id
      and d.search_type = v_search_type
      and d.country = ''
      and d.device = ''
      and (p_date_from is null or d.metric_date >= p_date_from)
      and (p_date_to is null or d.metric_date <= p_date_to);

    if p_compare_date_from is not null and p_compare_date_to is not null then
      select public.fn_gsc_metric_bundle(
        sum(d.clicks)::numeric,
        sum(d.impressions)::numeric,
        sum(coalesce(d.position, 0) * coalesce(d.impressions, 0))::numeric
      )
      into v_previous
      from public.project_search_console_property_daily d
      where d.project_id = p_project_id
        and d.search_type = v_search_type
        and d.country = ''
        and d.device = ''
        and d.metric_date >= p_compare_date_from
        and d.metric_date <= p_compare_date_to;
    end if;

    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'date', t.metric_date,
          'clicks', t.clicks,
          'impressions', t.impressions,
          'ctr', t.ctr,
          'position_avg', t.position_avg
        )
        order by t.metric_date
      ),
      '[]'::jsonb
    )
    into v_timeseries
    from (
      select
        d.metric_date,
        coalesce(sum(d.clicks), 0)::bigint as clicks,
        coalesce(sum(d.impressions), 0)::bigint as impressions,
        case
          when coalesce(sum(d.impressions), 0) = 0 then null
          else sum(d.clicks)::numeric / nullif(sum(d.impressions), 0)
        end as ctr,
        case
          when coalesce(sum(d.impressions), 0) = 0 then null
          else sum(coalesce(d.position, 0) * coalesce(d.impressions, 0))
               / nullif(sum(d.impressions), 0)
        end as position_avg
      from public.project_search_console_property_daily d
      where d.project_id = p_project_id
        and d.search_type = v_search_type
        and d.country = ''
        and d.device = ''
        and (p_date_from is null or d.metric_date >= p_date_from)
        and (p_date_to is null or d.metric_date <= p_date_to)
      group by d.metric_date
    ) t;
  else
    -- Fallback to page×query daily while property aggregates are empty
    select public.fn_gsc_metric_bundle(
      sum(d.clicks)::numeric,
      sum(d.impressions)::numeric,
      sum(coalesce(d.position, 0) * coalesce(d.impressions, 0))::numeric
    )
    into v_current
    from public.project_search_console_page_query_daily d
    where d.project_id = p_project_id
      and coalesce(d.search_type, 'web') = v_search_type
      and (p_date_from is null or d.metric_date >= p_date_from)
      and (p_date_to is null or d.metric_date <= p_date_to);

    if p_compare_date_from is not null and p_compare_date_to is not null then
      select public.fn_gsc_metric_bundle(
        sum(d.clicks)::numeric,
        sum(d.impressions)::numeric,
        sum(coalesce(d.position, 0) * coalesce(d.impressions, 0))::numeric
      )
      into v_previous
      from public.project_search_console_page_query_daily d
      where d.project_id = p_project_id
        and coalesce(d.search_type, 'web') = v_search_type
        and d.metric_date >= p_compare_date_from
        and d.metric_date <= p_compare_date_to;
    end if;

    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'date', t.metric_date,
          'clicks', t.clicks,
          'impressions', t.impressions,
          'ctr', t.ctr,
          'position_avg', t.position_avg
        )
        order by t.metric_date
      ),
      '[]'::jsonb
    )
    into v_timeseries
    from (
      select
        d.metric_date,
        coalesce(sum(d.clicks), 0)::bigint as clicks,
        coalesce(sum(d.impressions), 0)::bigint as impressions,
        case
          when coalesce(sum(d.impressions), 0) = 0 then null
          else sum(d.clicks)::numeric / nullif(sum(d.impressions), 0)
        end as ctr,
        case
          when coalesce(sum(d.impressions), 0) = 0 then null
          else sum(coalesce(d.position, 0) * coalesce(d.impressions, 0))
               / nullif(sum(d.impressions), 0)
        end as position_avg
      from public.project_search_console_page_query_daily d
      where d.project_id = p_project_id
        and coalesce(d.search_type, 'web') = v_search_type
        and (p_date_from is null or d.metric_date >= p_date_from)
        and (p_date_to is null or d.metric_date <= p_date_to)
      group by d.metric_date
    ) t;
  end if;

  -- Top queries (prefer query_daily)
  if exists (
    select 1 from public.project_search_console_query_daily q
    where q.project_id = p_project_id
      and q.search_type = v_search_type
      and (p_date_from is null or q.metric_date >= p_date_from)
      and (p_date_to is null or q.metric_date <= p_date_to)
    limit 1
  ) then
    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'query', r.query,
          'clicks', r.clicks,
          'impressions', r.impressions,
          'ctr', r.ctr,
          'position_avg', r.position_avg
        )
        order by r.clicks desc, r.impressions desc
      ),
      '[]'::jsonb
    )
    into v_queries
    from (
      select
        q.query,
        coalesce(sum(q.clicks), 0)::bigint as clicks,
        coalesce(sum(q.impressions), 0)::bigint as impressions,
        case
          when coalesce(sum(q.impressions), 0) = 0 then null
          else sum(q.clicks)::numeric / nullif(sum(q.impressions), 0)
        end as ctr,
        case
          when coalesce(sum(q.impressions), 0) = 0 then null
          else sum(coalesce(q.position, 0) * coalesce(q.impressions, 0))
               / nullif(sum(q.impressions), 0)
        end as position_avg
      from public.project_search_console_query_daily q
      where q.project_id = p_project_id
        and q.search_type = v_search_type
        and q.country = ''
        and q.device = ''
        and (p_date_from is null or q.metric_date >= p_date_from)
        and (p_date_to is null or q.metric_date <= p_date_to)
      group by q.query
      order by sum(q.clicks) desc nulls last, sum(q.impressions) desc nulls last
      limit v_limit
    ) r;
  else
    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'query', r.label,
          'clicks', r.clicks,
          'impressions', r.impressions,
          'ctr', r.ctr,
          'position_avg', r.position_avg
        )
        order by r.clicks desc, r.impressions desc
      ),
      '[]'::jsonb
    )
    into v_queries
    from (
      select
        d.query as label,
        coalesce(sum(d.clicks), 0)::bigint as clicks,
        coalesce(sum(d.impressions), 0)::bigint as impressions,
        case
          when coalesce(sum(d.impressions), 0) = 0 then null
          else sum(d.clicks)::numeric / nullif(sum(d.impressions), 0)
        end as ctr,
        case
          when coalesce(sum(d.impressions), 0) = 0 then null
          else sum(coalesce(d.position, 0) * coalesce(d.impressions, 0))
               / nullif(sum(d.impressions), 0)
        end as position_avg
      from public.project_search_console_page_query_daily d
      where d.project_id = p_project_id
        and coalesce(d.search_type, 'web') = v_search_type
        and (p_date_from is null or d.metric_date >= p_date_from)
        and (p_date_to is null or d.metric_date <= p_date_to)
      group by d.query
      order by sum(d.clicks) desc nulls last, sum(d.impressions) desc nulls last
      limit v_limit
    ) r;
  end if;

  -- Top pages
  if exists (
    select 1 from public.project_search_console_page_daily p
    where p.project_id = p_project_id
      and p.search_type = v_search_type
      and (p_date_from is null or p.metric_date >= p_date_from)
      and (p_date_to is null or p.metric_date <= p_date_to)
    limit 1
  ) then
    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'page', r.page_label,
          'clicks', r.clicks,
          'impressions', r.impressions,
          'ctr', r.ctr,
          'position_avg', r.position_avg
        )
        order by r.clicks desc, r.impressions desc
      ),
      '[]'::jsonb
    )
    into v_pages
    from (
      select
        coalesce(p.canonical_url, p.page_url) as page_label,
        coalesce(sum(p.clicks), 0)::bigint as clicks,
        coalesce(sum(p.impressions), 0)::bigint as impressions,
        case
          when coalesce(sum(p.impressions), 0) = 0 then null
          else sum(p.clicks)::numeric / nullif(sum(p.impressions), 0)
        end as ctr,
        case
          when coalesce(sum(p.impressions), 0) = 0 then null
          else sum(coalesce(p.position, 0) * coalesce(p.impressions, 0))
               / nullif(sum(p.impressions), 0)
        end as position_avg
      from public.project_search_console_page_daily p
      where p.project_id = p_project_id
        and p.search_type = v_search_type
        and p.country = ''
        and p.device = ''
        and (p_date_from is null or p.metric_date >= p_date_from)
        and (p_date_to is null or p.metric_date <= p_date_to)
      group by coalesce(p.canonical_url, p.page_url)
      order by sum(p.clicks) desc nulls last, sum(p.impressions) desc nulls last
      limit v_limit
    ) r;
  else
    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'page', r.page_label,
          'clicks', r.clicks,
          'impressions', r.impressions,
          'ctr', r.ctr,
          'position_avg', r.position_avg
        )
        order by r.clicks desc, r.impressions desc
      ),
      '[]'::jsonb
    )
    into v_pages
    from (
      select
        coalesce(d.canonical_url, d.page_url) as page_label,
        coalesce(sum(d.clicks), 0)::bigint as clicks,
        coalesce(sum(d.impressions), 0)::bigint as impressions,
        case
          when coalesce(sum(d.impressions), 0) = 0 then null
          else sum(d.clicks)::numeric / nullif(sum(d.impressions), 0)
        end as ctr,
        case
          when coalesce(sum(d.impressions), 0) = 0 then null
          else sum(coalesce(d.position, 0) * coalesce(d.impressions, 0))
               / nullif(sum(d.impressions), 0)
        end as position_avg
      from public.project_search_console_page_query_daily d
      where d.project_id = p_project_id
        and coalesce(d.search_type, 'web') = v_search_type
        and (p_date_from is null or d.metric_date >= p_date_from)
        and (p_date_to is null or d.metric_date <= p_date_to)
      group by coalesce(d.canonical_url, d.page_url)
      order by sum(d.clicks) desc nulls last, sum(d.impressions) desc nulls last
      limit v_limit
    ) r;
  end if;

  -- Opportunities from query aggregates (high impressions, low CTR / positions 4-20)
  select jsonb_build_object(
    'high_impressions_low_ctr', coalesce((
      select jsonb_agg(x order by x.impressions desc)
      from (
        select
          q.query,
          coalesce(sum(q.clicks), 0)::bigint as clicks,
          coalesce(sum(q.impressions), 0)::bigint as impressions,
          case
            when coalesce(sum(q.impressions), 0) = 0 then null
            else sum(q.clicks)::numeric / nullif(sum(q.impressions), 0)
          end as ctr,
          case
            when coalesce(sum(q.impressions), 0) = 0 then null
            else sum(coalesce(q.position, 0) * coalesce(q.impressions, 0))
                 / nullif(sum(q.impressions), 0)
          end as position_avg
        from public.project_search_console_query_daily q
        where q.project_id = p_project_id
          and q.search_type = v_search_type
          and q.country = ''
          and q.device = ''
          and (p_date_from is null or q.metric_date >= p_date_from)
          and (p_date_to is null or q.metric_date <= p_date_to)
        group by q.query
        having coalesce(sum(q.impressions), 0) >= 100
           and (
             coalesce(sum(q.clicks), 0)::numeric
             / nullif(sum(q.impressions), 0)
           ) < 0.02
        order by sum(q.impressions) desc
        limit 5
      ) x
    ), '[]'::jsonb),
    'positions_4_to_20', coalesce((
      select jsonb_agg(x order by x.impressions desc)
      from (
        select
          q.query,
          coalesce(sum(q.clicks), 0)::bigint as clicks,
          coalesce(sum(q.impressions), 0)::bigint as impressions,
          case
            when coalesce(sum(q.impressions), 0) = 0 then null
            else sum(q.clicks)::numeric / nullif(sum(q.impressions), 0)
          end as ctr,
          case
            when coalesce(sum(q.impressions), 0) = 0 then null
            else sum(coalesce(q.position, 0) * coalesce(q.impressions, 0))
                 / nullif(sum(q.impressions), 0)
          end as position_avg
        from public.project_search_console_query_daily q
        where q.project_id = p_project_id
          and q.search_type = v_search_type
          and q.country = ''
          and q.device = ''
          and (p_date_from is null or q.metric_date >= p_date_from)
          and (p_date_to is null or q.metric_date <= p_date_to)
        group by q.query
        having (
          sum(coalesce(q.position, 0) * coalesce(q.impressions, 0))
          / nullif(sum(q.impressions), 0)
        ) between 4 and 20
        order by sum(q.impressions) desc
        limit 5
      ) x
    ), '[]'::jsonb)
  )
  into v_opportunities;

  -- Monitored page indexation summary (latest snapshot per page)
  select jsonb_build_object(
    'scope', 'monitored_pages_only',
    'monitored_pages', coalesce((
      select count(*)::int
      from public.project_site_pages sp
      where sp.project_id = p_project_id
        and sp.is_active = true
    ), 0),
    'inspected', coalesce((
      select count(distinct s.site_page_id)::int
      from public.project_site_page_index_snapshots s
      where s.project_id = p_project_id
        and s.site_page_id is not null
        and s.inspection_status = 'succeeded'
    ), 0),
    'indexed', coalesce((
      select count(*)::int
      from (
        select distinct on (s.site_page_id) s.internal_issue_category, s.verdict
        from public.project_site_page_index_snapshots s
        where s.project_id = p_project_id
          and s.site_page_id is not null
          and s.inspection_status = 'succeeded'
        order by s.site_page_id, s.inspection_date desc
      ) latest
      where latest.internal_issue_category = 'indexed'
         or lower(coalesce(latest.verdict, '')) in ('pass', 'partial')
    ), 0),
    'not_indexed', coalesce((
      select count(*)::int
      from (
        select distinct on (s.site_page_id) s.internal_issue_category
        from public.project_site_page_index_snapshots s
        where s.project_id = p_project_id
          and s.site_page_id is not null
          and s.inspection_status = 'succeeded'
        order by s.site_page_id, s.inspection_date desc
      ) latest
      where latest.internal_issue_category in (
        'not_indexed',
        'discovered_not_indexed',
        'crawled_not_indexed',
        'blocked_by_robots',
        'blocked_by_noindex',
        'fetch_error',
        'server_error',
        'soft_404',
        'redirect',
        'duplicate'
      )
    ), 0),
    'with_issues', coalesce((
      select count(*)::int
      from (
        select distinct on (s.site_page_id)
          s.internal_issue_category,
          jsonb_array_length(coalesce(s.issues, '[]'::jsonb)) as issue_count
        from public.project_site_page_index_snapshots s
        where s.project_id = p_project_id
          and s.site_page_id is not null
          and s.inspection_status = 'succeeded'
        order by s.site_page_id, s.inspection_date desc
      ) latest
      where latest.issue_count > 0
         or latest.internal_issue_category in (
           'canonical_mismatch',
           'rich_result_issue',
           'blocked_by_robots',
           'blocked_by_noindex',
           'fetch_error',
           'server_error',
           'soft_404'
         )
    ), 0),
    'not_inspected', greatest(
      coalesce((
        select count(*)::int
        from public.project_site_pages sp
        where sp.project_id = p_project_id
          and sp.is_active = true
      ), 0)
      - coalesce((
        select count(distinct s.site_page_id)::int
        from public.project_site_page_index_snapshots s
        where s.project_id = p_project_id
          and s.site_page_id is not null
          and s.inspection_status = 'succeeded'
      ), 0),
      0
    ),
    'last_inspection_at', (
      select max(s.inspection_date)
      from public.project_site_page_index_snapshots s
      where s.project_id = p_project_id
    )
  )
  into v_indexation;

  return jsonb_build_object(
    'project_id', p_project_id,
    'connected', coalesce(v_connected, false),
    'property', v_property,
    'search_type', v_search_type,
    'date_from', p_date_from,
    'date_to', p_date_to,
    'compare_date_from', p_compare_date_from,
    'compare_date_to', p_compare_date_to,
    'latest_metric_date', v_latest_metric_date,
    'last_synced_at', v_last_synced_at,
    'coverage_note',
      'Query–page rows from Search Console may be partial. Indexation covers monitored project pages only.',
    'current', coalesce(v_current, public.fn_gsc_metric_bundle(0, 0, 0)),
    'previous', v_previous,
    'timeseries', coalesce(v_timeseries, '[]'::jsonb),
    'top_queries', coalesce(v_queries, '[]'::jsonb),
    'top_pages', coalesce(v_pages, '[]'::jsonb),
    'opportunities', coalesce(v_opportunities, '{}'::jsonb),
    'indexation', coalesce(v_indexation, '{}'::jsonb)
  );
end;
$$;

revoke all on function public.fn_get_project_search_overview(integer, date, date, date, date, text, integer) from public;
grant execute on function public.fn_get_project_search_overview(integer, date, date, date, date, text, integer) to authenticated;
grant execute on function public.fn_get_project_search_overview(integer, date, date, date, date, text, integer) to service_role;

-- ---------------------------------------------------------------------------
-- 11) Queries / pages / indexation / sitemaps RPCs
-- ---------------------------------------------------------------------------

create or replace function public.fn_get_project_search_queries(
  p_project_id integer,
  p_date_from date default null,
  p_date_to date default null,
  p_search_type text default 'web',
  p_limit integer default 100,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security invoker
set search_path to 'pg_catalog', 'public'
as $$
declare
  v_limit integer := least(greatest(coalesce(p_limit, 100), 1), 500);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_search_type text := coalesce(nullif(trim(p_search_type), ''), 'web');
  v_rows jsonb;
  v_total integer;
begin
  if p_project_id is null or not public.can_edit_project(p_project_id) then
    raise exception 'forbidden';
  end if;

  if exists (
    select 1 from public.project_search_console_query_daily q
    where q.project_id = p_project_id and q.search_type = v_search_type
    limit 1
  ) then
    select count(*)::int into v_total
    from (
      select q.query
      from public.project_search_console_query_daily q
      where q.project_id = p_project_id
        and q.search_type = v_search_type
        and q.country = ''
        and q.device = ''
        and (p_date_from is null or q.metric_date >= p_date_from)
        and (p_date_to is null or q.metric_date <= p_date_to)
      group by q.query
    ) t;

    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'query', r.query,
          'clicks', r.clicks,
          'impressions', r.impressions,
          'ctr', r.ctr,
          'position_avg', r.position_avg,
          'first_seen_at', r.first_seen_at,
          'last_seen_at', r.last_seen_at
        )
        order by r.clicks desc, r.impressions desc
      ),
      '[]'::jsonb
    )
    into v_rows
    from (
      select
        q.query,
        coalesce(sum(q.clicks), 0)::bigint as clicks,
        coalesce(sum(q.impressions), 0)::bigint as impressions,
        case
          when coalesce(sum(q.impressions), 0) = 0 then null
          else sum(q.clicks)::numeric / nullif(sum(q.impressions), 0)
        end as ctr,
        case
          when coalesce(sum(q.impressions), 0) = 0 then null
          else sum(coalesce(q.position, 0) * coalesce(q.impressions, 0))
               / nullif(sum(q.impressions), 0)
        end as position_avg,
        min(coalesce(q.first_seen_at, q.metric_date)) as first_seen_at,
        max(coalesce(q.last_seen_at, q.metric_date)) as last_seen_at
      from public.project_search_console_query_daily q
      where q.project_id = p_project_id
        and q.search_type = v_search_type
        and q.country = ''
        and q.device = ''
        and (p_date_from is null or q.metric_date >= p_date_from)
        and (p_date_to is null or q.metric_date <= p_date_to)
      group by q.query
      order by sum(q.clicks) desc nulls last, sum(q.impressions) desc nulls last
      limit v_limit offset v_offset
    ) r;
  else
    select count(*)::int into v_total
    from (
      select d.query
      from public.project_search_console_page_query_daily d
      where d.project_id = p_project_id
        and coalesce(d.search_type, 'web') = v_search_type
        and (p_date_from is null or d.metric_date >= p_date_from)
        and (p_date_to is null or d.metric_date <= p_date_to)
      group by d.query
    ) t;

    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'query', r.query,
          'clicks', r.clicks,
          'impressions', r.impressions,
          'ctr', r.ctr,
          'position_avg', r.position_avg,
          'first_seen_at', r.first_seen_at,
          'last_seen_at', r.last_seen_at
        )
        order by r.clicks desc, r.impressions desc
      ),
      '[]'::jsonb
    )
    into v_rows
    from (
      select
        d.query,
        coalesce(sum(d.clicks), 0)::bigint as clicks,
        coalesce(sum(d.impressions), 0)::bigint as impressions,
        case
          when coalesce(sum(d.impressions), 0) = 0 then null
          else sum(d.clicks)::numeric / nullif(sum(d.impressions), 0)
        end as ctr,
        case
          when coalesce(sum(d.impressions), 0) = 0 then null
          else sum(coalesce(d.position, 0) * coalesce(d.impressions, 0))
               / nullif(sum(d.impressions), 0)
        end as position_avg,
        min(d.metric_date) as first_seen_at,
        max(d.metric_date) as last_seen_at
      from public.project_search_console_page_query_daily d
      where d.project_id = p_project_id
        and coalesce(d.search_type, 'web') = v_search_type
        and (p_date_from is null or d.metric_date >= p_date_from)
        and (p_date_to is null or d.metric_date <= p_date_to)
      group by d.query
      order by sum(d.clicks) desc nulls last, sum(d.impressions) desc nulls last
      limit v_limit offset v_offset
    ) r;
  end if;

  return jsonb_build_object(
    'project_id', p_project_id,
    'date_from', p_date_from,
    'date_to', p_date_to,
    'search_type', v_search_type,
    'total', coalesce(v_total, 0),
    'limit', v_limit,
    'offset', v_offset,
    'rows', coalesce(v_rows, '[]'::jsonb),
    'coverage_note',
      'Rows reflect Search Console response coverage and may be partial.'
  );
end;
$$;

revoke all on function public.fn_get_project_search_queries(integer, date, date, text, integer, integer) from public;
grant execute on function public.fn_get_project_search_queries(integer, date, date, text, integer, integer) to authenticated;
grant execute on function public.fn_get_project_search_queries(integer, date, date, text, integer, integer) to service_role;

create or replace function public.fn_get_project_search_pages(
  p_project_id integer,
  p_date_from date default null,
  p_date_to date default null,
  p_search_type text default 'web',
  p_limit integer default 100,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security invoker
set search_path to 'pg_catalog', 'public'
as $$
declare
  v_limit integer := least(greatest(coalesce(p_limit, 100), 1), 500);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_search_type text := coalesce(nullif(trim(p_search_type), ''), 'web');
  v_rows jsonb;
  v_total integer;
begin
  if p_project_id is null or not public.can_edit_project(p_project_id) then
    raise exception 'forbidden';
  end if;

  if exists (
    select 1 from public.project_search_console_page_daily p
    where p.project_id = p_project_id and p.search_type = v_search_type
    limit 1
  ) then
    select count(*)::int into v_total
    from (
      select coalesce(p.canonical_url, p.page_url) as page_label
      from public.project_search_console_page_daily p
      where p.project_id = p_project_id
        and p.search_type = v_search_type
        and p.country = ''
        and p.device = ''
        and (p_date_from is null or p.metric_date >= p_date_from)
        and (p_date_to is null or p.metric_date <= p_date_to)
      group by coalesce(p.canonical_url, p.page_url)
    ) t;

    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'page', r.page_label,
          'clicks', r.clicks,
          'impressions', r.impressions,
          'ctr', r.ctr,
          'position_avg', r.position_avg,
          'site_page_id', r.site_page_id
        )
        order by r.clicks desc, r.impressions desc
      ),
      '[]'::jsonb
    )
    into v_rows
    from (
      select
        coalesce(p.canonical_url, p.page_url) as page_label,
        max(p.site_page_id) as site_page_id,
        coalesce(sum(p.clicks), 0)::bigint as clicks,
        coalesce(sum(p.impressions), 0)::bigint as impressions,
        case
          when coalesce(sum(p.impressions), 0) = 0 then null
          else sum(p.clicks)::numeric / nullif(sum(p.impressions), 0)
        end as ctr,
        case
          when coalesce(sum(p.impressions), 0) = 0 then null
          else sum(coalesce(p.position, 0) * coalesce(p.impressions, 0))
               / nullif(sum(p.impressions), 0)
        end as position_avg
      from public.project_search_console_page_daily p
      where p.project_id = p_project_id
        and p.search_type = v_search_type
        and p.country = ''
        and p.device = ''
        and (p_date_from is null or p.metric_date >= p_date_from)
        and (p_date_to is null or p.metric_date <= p_date_to)
      group by coalesce(p.canonical_url, p.page_url)
      order by sum(p.clicks) desc nulls last, sum(p.impressions) desc nulls last
      limit v_limit offset v_offset
    ) r;
  else
    select count(*)::int into v_total
    from (
      select coalesce(d.canonical_url, d.page_url) as page_label
      from public.project_search_console_page_query_daily d
      where d.project_id = p_project_id
        and coalesce(d.search_type, 'web') = v_search_type
        and (p_date_from is null or d.metric_date >= p_date_from)
        and (p_date_to is null or d.metric_date <= p_date_to)
      group by coalesce(d.canonical_url, d.page_url)
    ) t;

    select coalesce(
      jsonb_agg(
        jsonb_build_object(
          'page', r.page_label,
          'clicks', r.clicks,
          'impressions', r.impressions,
          'ctr', r.ctr,
          'position_avg', r.position_avg,
          'site_page_id', r.site_page_id
        )
        order by r.clicks desc, r.impressions desc
      ),
      '[]'::jsonb
    )
    into v_rows
    from (
      select
        coalesce(d.canonical_url, d.page_url) as page_label,
        max(d.site_page_id) as site_page_id,
        coalesce(sum(d.clicks), 0)::bigint as clicks,
        coalesce(sum(d.impressions), 0)::bigint as impressions,
        case
          when coalesce(sum(d.impressions), 0) = 0 then null
          else sum(d.clicks)::numeric / nullif(sum(d.impressions), 0)
        end as ctr,
        case
          when coalesce(sum(d.impressions), 0) = 0 then null
          else sum(coalesce(d.position, 0) * coalesce(d.impressions, 0))
               / nullif(sum(d.impressions), 0)
        end as position_avg
      from public.project_search_console_page_query_daily d
      where d.project_id = p_project_id
        and coalesce(d.search_type, 'web') = v_search_type
        and (p_date_from is null or d.metric_date >= p_date_from)
        and (p_date_to is null or d.metric_date <= p_date_to)
      group by coalesce(d.canonical_url, d.page_url)
      order by sum(d.clicks) desc nulls last, sum(d.impressions) desc nulls last
      limit v_limit offset v_offset
    ) r;
  end if;

  return jsonb_build_object(
    'project_id', p_project_id,
    'date_from', p_date_from,
    'date_to', p_date_to,
    'search_type', v_search_type,
    'total', coalesce(v_total, 0),
    'limit', v_limit,
    'offset', v_offset,
    'rows', coalesce(v_rows, '[]'::jsonb)
  );
end;
$$;

revoke all on function public.fn_get_project_search_pages(integer, date, date, text, integer, integer) from public;
grant execute on function public.fn_get_project_search_pages(integer, date, date, text, integer, integer) to authenticated;
grant execute on function public.fn_get_project_search_pages(integer, date, date, text, integer, integer) to service_role;

create or replace function public.fn_get_project_indexation_summary(
  p_project_id integer
)
returns jsonb
language plpgsql
stable
security invoker
set search_path to 'pg_catalog', 'public'
as $$
declare
  v_overview jsonb;
begin
  if p_project_id is null or not public.can_edit_project(p_project_id) then
    raise exception 'forbidden';
  end if;

  select (public.fn_get_project_search_overview(
    p_project_id, null, null, null, null, 'web', 1
  ))->'indexation'
  into v_overview;

  return jsonb_build_object(
    'project_id', p_project_id,
    'indexation', coalesce(v_overview, '{}'::jsonb),
    'note',
      'Indexation status covers monitored project pages only, not the full site.'
  );
end;
$$;

revoke all on function public.fn_get_project_indexation_summary(integer) from public;
grant execute on function public.fn_get_project_indexation_summary(integer) to authenticated;
grant execute on function public.fn_get_project_indexation_summary(integer) to service_role;

create or replace function public.fn_get_project_search_sitemaps(
  p_project_id integer
)
returns jsonb
language plpgsql
stable
security invoker
set search_path to 'pg_catalog', 'public'
as $$
declare
  v_rows jsonb;
begin
  if p_project_id is null or not public.can_edit_project(p_project_id) then
    raise exception 'forbidden';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', s.id,
        'path', s.path,
        'sitemap_type', s.sitemap_type,
        'is_pending', s.is_pending,
        'is_sitemap_index', s.is_sitemap_index,
        'last_submitted_at', s.last_submitted_at,
        'last_downloaded_at', s.last_downloaded_at,
        'submitted_urls_count', s.submitted_urls_count,
        'warnings_count', s.warnings_count,
        'errors_count', s.errors_count,
        'contents', s.contents,
        'last_seen_at', s.last_seen_at
      )
      order by s.errors_count desc nulls last, s.path
    ),
    '[]'::jsonb
  )
  into v_rows
  from public.project_search_console_sitemaps s
  where s.project_id = p_project_id;

  return jsonb_build_object(
    'project_id', p_project_id,
    'rows', coalesce(v_rows, '[]'::jsonb),
    'note', 'Sitemap indexed-URL counts from the deprecated API field are not used.'
  );
end;
$$;

revoke all on function public.fn_get_project_search_sitemaps(integer) from public;
grant execute on function public.fn_get_project_search_sitemaps(integer) to authenticated;
grant execute on function public.fn_get_project_search_sitemaps(integer) to service_role;

create or replace function public.fn_enqueue_site_page_inspection(
  p_project_id integer,
  p_site_page_id bigint default null,
  p_url text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_property_id bigint;
  v_url text;
  v_page_id bigint;
  v_queue_id bigint;
begin
  if p_project_id is null or not public.can_edit_project(p_project_id) then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  select p.id
  into v_property_id
  from public.project_search_console_properties p
  where p.project_id = p_project_id
    and p.is_active = true
  order by p.updated_at desc
  limit 1;

  if v_property_id is null then
    raise exception 'Search Console property not connected';
  end if;

  if p_site_page_id is not null then
    select sp.id, coalesce(sp.canonical_url, sp.url)
    into v_page_id, v_url
    from public.project_site_pages sp
    where sp.id = p_site_page_id
      and sp.project_id = p_project_id
      and sp.is_active = true;
  elsif p_url is not null and length(trim(p_url)) > 0 then
    v_url := trim(p_url);
    select sp.id
    into v_page_id
    from public.project_site_pages sp
    where sp.project_id = p_project_id
      and sp.is_active = true
      and (sp.canonical_url = v_url or sp.url = v_url)
    limit 1;
  else
    raise exception 'site_page_id or url is required';
  end if;

  if v_url is null or length(v_url) = 0 then
    raise exception 'URL not found';
  end if;

  insert into public.project_search_console_inspect_queue (
    project_id,
    property_id,
    site_page_id,
    url,
    priority,
    status,
    requested_by_auth_user_id,
    scheduled_for
  )
  values (
    p_project_id,
    v_property_id,
    v_page_id,
    v_url,
    10,
    'queued',
    auth.uid(),
    now()
  )
  on conflict do nothing
  returning id into v_queue_id;

  if v_queue_id is null then
    select q.id into v_queue_id
    from public.project_search_console_inspect_queue q
    where q.property_id = v_property_id
      and q.url = v_url
      and q.status in ('queued', 'running')
    limit 1;
  end if;

  return jsonb_build_object(
    'ok', true,
    'queue_id', v_queue_id,
    'url', v_url,
    'site_page_id', v_page_id
  );
end;
$$;

revoke all on function public.fn_enqueue_site_page_inspection(integer, bigint, text) from public;
grant execute on function public.fn_enqueue_site_page_inspection(integer, bigint, text) to authenticated;
grant execute on function public.fn_enqueue_site_page_inspection(integer, bigint, text) to service_role;
