-- Project-scoped competitor social monitoring (Bright Data).
-- LinkedIn is supported but not required when creating a competitor.
-- Idempotent: safe if tables already exist.

create table if not exists public.project_competitors (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  name text not null,
  website_url text null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_competitors_name_check check (char_length(trim(name)) > 0)
);

create index if not exists idx_project_competitors_project
  on public.project_competitors(project_id, is_active, name);

create table if not exists public.project_competitor_social_profiles (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  competitor_id bigint not null references public.project_competitors(id) on delete cascade,
  network text not null,
  profile_url text not null,
  profile_url_normalized text not null,
  external_profile_id text null,
  is_active boolean not null default true,
  last_synced_at timestamptz null,
  last_sync_status text null,
  last_sync_error text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_competitor_social_profiles_network_check check (
    network in ('linkedin', 'instagram', 'facebook', 'youtube', 'tiktok', 'x')
  ),
  constraint project_competitor_social_profiles_status_check check (
    last_sync_status is null
    or last_sync_status in ('queued', 'running', 'succeeded', 'failed', 'partial')
  ),
  constraint project_competitor_social_profiles_unique_profile
    unique (competitor_id, network, profile_url_normalized)
);

create index if not exists idx_project_competitor_social_profiles_project
  on public.project_competitor_social_profiles(project_id, is_active);

create table if not exists public.project_competitor_social_posts (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  competitor_id bigint not null references public.project_competitors(id) on delete cascade,
  social_profile_id bigint not null
    references public.project_competitor_social_profiles(id) on delete cascade,
  network text not null,
  external_post_id text null,
  dedupe_key text not null,
  post_url text not null,
  published_at timestamptz null,
  text_content text null,
  media_type text null,
  media_urls jsonb not null default '[]'::jsonb,
  thumbnail_url text null,
  reactions_count integer null,
  comments_count integer null,
  shares_count integer null,
  views_count integer null,
  followers_count_at_sync integer null,
  extra_metrics jsonb not null default '{}'::jsonb,
  raw_payload jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_competitor_social_posts_network_check check (
    network in ('linkedin', 'instagram', 'facebook', 'youtube', 'tiktok', 'x')
  ),
  constraint project_competitor_social_posts_media_urls_array check (
    jsonb_typeof(media_urls) = 'array'
  ),
  constraint project_competitor_social_posts_unique_dedupe
    unique (social_profile_id, dedupe_key)
);

create index if not exists idx_project_competitor_social_posts_project_published
  on public.project_competitor_social_posts(project_id, published_at desc nulls last);

create table if not exists public.project_competitor_sync_runs (
  id uuid primary key default gen_random_uuid(),
  project_id integer null references public.projects(id) on delete cascade,
  competitor_id bigint null references public.project_competitors(id) on delete set null,
  social_profile_id bigint null
    references public.project_competitor_social_profiles(id) on delete set null,
  network text null,
  trigger_type text not null,
  status text not null default 'queued',
  started_at timestamptz null,
  finished_at timestamptz null,
  posts_found integer not null default 0,
  posts_created integer not null default 0,
  posts_updated integer not null default 0,
  error_message text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_competitor_sync_runs_trigger_check check (
    trigger_type in ('manual', 'automatic')
  ),
  constraint project_competitor_sync_runs_status_check check (
    status in ('queued', 'running', 'succeeded', 'failed', 'partial')
  ),
  constraint project_competitor_sync_runs_network_check check (
    network is null
    or network in ('linkedin', 'instagram', 'facebook', 'youtube', 'tiktok', 'x')
  )
);

create index if not exists idx_project_competitor_sync_runs_project
  on public.project_competitor_sync_runs(project_id, created_at desc);

create table if not exists public.app_runtime_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

insert into public.app_runtime_settings (key, value)
values (
  'competitor_social_sync',
  jsonb_build_object(
    'cron_hour_utc', 6,
    'first_sync_days', 30,
    'max_posts_per_profile', 50
  )
)
on conflict (key) do nothing;

alter table public.project_competitors enable row level security;
alter table public.project_competitor_social_profiles enable row level security;
alter table public.project_competitor_social_posts enable row level security;
alter table public.project_competitor_sync_runs enable row level security;
alter table public.app_runtime_settings enable row level security;

drop policy if exists project_competitors_select on public.project_competitors;
create policy project_competitors_select
  on public.project_competitors for select to authenticated
  using (public.can_edit_project(project_id));

drop policy if exists project_competitors_insert on public.project_competitors;
create policy project_competitors_insert
  on public.project_competitors for insert to authenticated
  with check (public.can_edit_project(project_id));

drop policy if exists project_competitors_update on public.project_competitors;
create policy project_competitors_update
  on public.project_competitors for update to authenticated
  using (public.can_edit_project(project_id))
  with check (public.can_edit_project(project_id));

drop policy if exists project_competitors_delete on public.project_competitors;
create policy project_competitors_delete
  on public.project_competitors for delete to authenticated
  using (public.can_edit_project(project_id));

drop policy if exists project_competitor_social_profiles_select
  on public.project_competitor_social_profiles;
create policy project_competitor_social_profiles_select
  on public.project_competitor_social_profiles for select to authenticated
  using (public.can_edit_project(project_id));

drop policy if exists project_competitor_social_profiles_insert
  on public.project_competitor_social_profiles;
create policy project_competitor_social_profiles_insert
  on public.project_competitor_social_profiles for insert to authenticated
  with check (public.can_edit_project(project_id));

drop policy if exists project_competitor_social_profiles_update
  on public.project_competitor_social_profiles;
create policy project_competitor_social_profiles_update
  on public.project_competitor_social_profiles for update to authenticated
  using (public.can_edit_project(project_id))
  with check (public.can_edit_project(project_id));

drop policy if exists project_competitor_social_profiles_delete
  on public.project_competitor_social_profiles;
create policy project_competitor_social_profiles_delete
  on public.project_competitor_social_profiles for delete to authenticated
  using (public.can_edit_project(project_id));

drop policy if exists project_competitor_social_posts_select
  on public.project_competitor_social_posts;
create policy project_competitor_social_posts_select
  on public.project_competitor_social_posts for select to authenticated
  using (public.can_edit_project(project_id));

revoke insert, update, delete on public.project_competitor_social_posts from authenticated;

drop policy if exists project_competitor_sync_runs_select
  on public.project_competitor_sync_runs;
create policy project_competitor_sync_runs_select
  on public.project_competitor_sync_runs for select to authenticated
  using (project_id is not null and public.can_edit_project(project_id));

revoke insert, update, delete on public.project_competitor_sync_runs from authenticated;

drop policy if exists app_runtime_settings_select on public.app_runtime_settings;
create policy app_runtime_settings_select
  on public.app_runtime_settings for select to authenticated
  using (true);

revoke insert, update, delete on public.app_runtime_settings from authenticated;

grant select, insert, update, delete on public.project_competitors to authenticated;
grant select, insert, update, delete on public.project_competitor_social_profiles to authenticated;
grant select on public.project_competitor_social_posts to authenticated;
grant select on public.project_competitor_sync_runs to authenticated;
grant select on public.app_runtime_settings to authenticated;
