-- Phase 1: owned brand social profiles + unified social posts layer.
-- Does not recreate competitor monitoring; extends it.

-- ---------------------------------------------------------------------------
-- 1) Brand (owned) social profiles
-- ---------------------------------------------------------------------------

create table if not exists public.project_brand_social_profiles (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  network text not null,
  profile_url text not null,
  profile_url_normalized text not null,
  external_profile_id text null,
  is_active boolean not null default true,
  last_synced_at timestamptz null,
  last_sync_status text null,
  last_sync_error text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_brand_social_profiles_network_check check (
    network in ('linkedin', 'instagram', 'facebook', 'youtube', 'tiktok', 'x')
  ),
  constraint project_brand_social_profiles_status_check check (
    last_sync_status is null
    or last_sync_status in ('queued', 'running', 'succeeded', 'failed', 'partial')
  ),
  constraint project_brand_social_profiles_url_not_blank check (
    char_length(trim(profile_url)) > 0
  ),
  constraint project_brand_social_profiles_unique_profile
    unique (project_id, network, profile_url_normalized)
);

create index if not exists idx_project_brand_social_profiles_project
  on public.project_brand_social_profiles(project_id, is_active);

create index if not exists idx_project_brand_social_profiles_sync
  on public.project_brand_social_profiles(is_active, last_synced_at)
  where is_active = true;

-- ---------------------------------------------------------------------------
-- 2) Generalize competitor posts to support owned posts
-- ---------------------------------------------------------------------------

alter table public.project_competitor_social_posts
  add column if not exists entity_type text;

alter table public.project_competitor_social_posts
  add column if not exists brand_social_profile_id bigint null
    references public.project_brand_social_profiles(id) on delete cascade;

-- Backfill existing rows as competitor posts.
update public.project_competitor_social_posts
set entity_type = 'competitor'
where entity_type is null;

alter table public.project_competitor_social_posts
  alter column entity_type set default 'competitor';

alter table public.project_competitor_social_posts
  alter column entity_type set not null;

-- Allow owned posts (no competitor).
alter table public.project_competitor_social_posts
  alter column competitor_id drop not null;

alter table public.project_competitor_social_posts
  alter column social_profile_id drop not null;

alter table public.project_competitor_social_posts
  drop constraint if exists project_competitor_social_posts_entity_check;

alter table public.project_competitor_social_posts
  add constraint project_competitor_social_posts_entity_check check (
    (
      entity_type = 'competitor'
      and competitor_id is not null
      and social_profile_id is not null
      and brand_social_profile_id is null
    )
    or (
      entity_type = 'owned'
      and brand_social_profile_id is not null
      and competitor_id is null
      and social_profile_id is null
    )
  );

alter table public.project_competitor_social_posts
  drop constraint if exists project_competitor_social_posts_entity_type_check;

alter table public.project_competitor_social_posts
  add constraint project_competitor_social_posts_entity_type_check check (
    entity_type in ('owned', 'competitor')
  );

-- Dedupe for owned posts (competitor unique already exists on social_profile_id + dedupe_key).
create unique index if not exists project_competitor_social_posts_owned_dedupe
  on public.project_competitor_social_posts(brand_social_profile_id, dedupe_key)
  where entity_type = 'owned' and brand_social_profile_id is not null;

create index if not exists idx_project_social_posts_entity_published
  on public.project_competitor_social_posts(project_id, entity_type, published_at desc nulls last);

create index if not exists idx_project_social_posts_network_external
  on public.project_competitor_social_posts(project_id, network, external_post_id)
  where external_post_id is not null;

create index if not exists idx_project_social_posts_brand_profile
  on public.project_competitor_social_posts(brand_social_profile_id, published_at desc nulls last)
  where brand_social_profile_id is not null;

-- ---------------------------------------------------------------------------
-- 3) Sync runs: support brand profile runs
-- ---------------------------------------------------------------------------

alter table public.project_competitor_sync_runs
  add column if not exists brand_social_profile_id bigint null
    references public.project_brand_social_profiles(id) on delete set null;

alter table public.project_competitor_sync_runs
  add column if not exists entity_type text null;

alter table public.project_competitor_sync_runs
  drop constraint if exists project_competitor_sync_runs_entity_type_check;

alter table public.project_competitor_sync_runs
  add constraint project_competitor_sync_runs_entity_type_check check (
    entity_type is null or entity_type in ('owned', 'competitor')
  );

create index if not exists idx_project_competitor_sync_runs_brand_profile
  on public.project_competitor_sync_runs(brand_social_profile_id, created_at desc)
  where brand_social_profile_id is not null;

-- ---------------------------------------------------------------------------
-- 4) Daily follower/posts snapshots (owned + competitor)
-- ---------------------------------------------------------------------------

create table if not exists public.project_social_profile_daily_snapshots (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  entity_type text not null,
  brand_social_profile_id bigint null
    references public.project_brand_social_profiles(id) on delete cascade,
  competitor_social_profile_id bigint null
    references public.project_competitor_social_profiles(id) on delete cascade,
  snapshot_date date not null,
  followers_count integer null,
  posts_count integer null,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint project_social_profile_daily_snapshots_entity_type_check check (
    entity_type in ('owned', 'competitor')
  ),
  constraint project_social_profile_daily_snapshots_entity_check check (
    (
      entity_type = 'owned'
      and brand_social_profile_id is not null
      and competitor_social_profile_id is null
    )
    or (
      entity_type = 'competitor'
      and competitor_social_profile_id is not null
      and brand_social_profile_id is null
    )
  )
);

create unique index if not exists project_social_snapshots_owned_unique
  on public.project_social_profile_daily_snapshots(brand_social_profile_id, snapshot_date)
  where entity_type = 'owned' and brand_social_profile_id is not null;

create unique index if not exists project_social_snapshots_competitor_unique
  on public.project_social_profile_daily_snapshots(competitor_social_profile_id, snapshot_date)
  where entity_type = 'competitor' and competitor_social_profile_id is not null;

create index if not exists idx_project_social_snapshots_project_date
  on public.project_social_profile_daily_snapshots(project_id, snapshot_date desc);

-- ---------------------------------------------------------------------------
-- 5) Unified views
-- ---------------------------------------------------------------------------

create or replace view public.v_project_social_entities
with (security_invoker = true)
as
select
  p.id as project_id,
  ('owned:' || p.id::text) as entity_id,
  coalesce(nullif(trim(p.name), ''), 'Our brand') as entity_name,
  'owned'::text as entity_type,
  true as is_owned
from public.projects p
where coalesce(p.is_deleted, false) = false
  and coalesce(p.active, true) = true

union all

select
  c.project_id,
  ('competitor:' || c.id::text) as entity_id,
  c.name as entity_name,
  'competitor'::text as entity_type,
  false as is_owned
from public.project_competitors c
where c.is_active = true;

create or replace view public.v_project_social_posts
with (security_invoker = true)
as
select
  posts.id,
  posts.project_id,
  case
    when posts.entity_type = 'owned' then ('owned:' || posts.project_id::text)
    else ('competitor:' || posts.competitor_id::text)
  end as entity_id,
  posts.entity_type,
  (posts.entity_type = 'owned') as is_owned,
  case
    when posts.entity_type = 'owned' then coalesce(nullif(trim(proj.name), ''), 'Our brand')
    else c.name
  end as entity_name,
  posts.network,
  posts.external_post_id,
  posts.post_url,
  posts.published_at,
  posts.text_content,
  posts.media_type,
  posts.media_urls,
  posts.thumbnail_url,
  posts.reactions_count,
  posts.comments_count,
  posts.shares_count,
  posts.views_count,
  posts.followers_count_at_sync,
  posts.extra_metrics,
  posts.last_seen_at,
  posts.created_at,
  posts.updated_at,
  posts.competitor_id,
  posts.social_profile_id,
  posts.brand_social_profile_id,
  posts.dedupe_key
from public.project_competitor_social_posts posts
left join public.projects proj
  on proj.id = posts.project_id
left join public.project_competitors c
  on c.id = posts.competitor_id;

-- ---------------------------------------------------------------------------
-- 6) RLS
-- ---------------------------------------------------------------------------

alter table public.project_brand_social_profiles enable row level security;
alter table public.project_social_profile_daily_snapshots enable row level security;

drop policy if exists project_brand_social_profiles_select on public.project_brand_social_profiles;
create policy project_brand_social_profiles_select
  on public.project_brand_social_profiles for select to authenticated
  using (public.can_edit_project(project_id));

drop policy if exists project_brand_social_profiles_insert on public.project_brand_social_profiles;
create policy project_brand_social_profiles_insert
  on public.project_brand_social_profiles for insert to authenticated
  with check (public.can_edit_project(project_id));

drop policy if exists project_brand_social_profiles_update on public.project_brand_social_profiles;
create policy project_brand_social_profiles_update
  on public.project_brand_social_profiles for update to authenticated
  using (public.can_edit_project(project_id))
  with check (public.can_edit_project(project_id));

drop policy if exists project_brand_social_profiles_delete on public.project_brand_social_profiles;
create policy project_brand_social_profiles_delete
  on public.project_brand_social_profiles for delete to authenticated
  using (public.can_edit_project(project_id));

drop policy if exists project_social_profile_daily_snapshots_select
  on public.project_social_profile_daily_snapshots;
create policy project_social_profile_daily_snapshots_select
  on public.project_social_profile_daily_snapshots for select to authenticated
  using (public.can_edit_project(project_id));

revoke insert, update, delete on public.project_social_profile_daily_snapshots from authenticated;

grant select, insert, update, delete on public.project_brand_social_profiles to authenticated;
grant select on public.project_social_profile_daily_snapshots to authenticated;
grant select on public.v_project_social_entities to authenticated;
grant select on public.v_project_social_posts to authenticated;

do $$
begin
  grant usage, select on sequence public.project_brand_social_profiles_id_seq to authenticated;
exception
  when undefined_table then null;
end $$;

do $$
begin
  grant usage, select on sequence public.project_social_profile_daily_snapshots_id_seq to authenticated;
exception
  when undefined_table then null;
end $$;

-- ---------------------------------------------------------------------------
-- 7) List posts RPC (unified, filterable)
-- ---------------------------------------------------------------------------

create or replace function public.fn_list_project_social_posts(
  p_project_id integer,
  p_date_from timestamptz default null,
  p_date_to timestamptz default null,
  p_networks text[] default null,
  p_entity_ids text[] default null,
  p_media_types text[] default null,
  p_limit integer default 100
)
returns setof public.v_project_social_posts
language plpgsql
stable
security invoker
set search_path to 'pg_catalog', 'public'
as $$
begin
  if p_project_id is null or not public.can_edit_project(p_project_id) then
    raise exception 'forbidden';
  end if;

  return query
  select v.*
  from public.v_project_social_posts v
  where v.project_id = p_project_id
    and (p_date_from is null or v.published_at >= p_date_from)
    and (p_date_to is null or v.published_at <= p_date_to)
    and (p_networks is null or cardinality(p_networks) = 0 or v.network = any (p_networks))
    and (p_entity_ids is null or cardinality(p_entity_ids) = 0 or v.entity_id = any (p_entity_ids))
    and (
      p_media_types is null
      or cardinality(p_media_types) = 0
      or coalesce(v.media_type, 'unknown') = any (p_media_types)
    )
  order by v.published_at desc nulls last, v.id desc
  limit greatest(1, least(coalesce(p_limit, 100), 500));
end;
$$;

revoke all on function public.fn_list_project_social_posts(
  integer, timestamptz, timestamptz, text[], text[], text[], integer
) from public;
grant execute on function public.fn_list_project_social_posts(
  integer, timestamptz, timestamptz, text[], text[], text[], integer
) to authenticated;
grant execute on function public.fn_list_project_social_posts(
  integer, timestamptz, timestamptz, text[], text[], text[], integer
) to service_role;
