-- Competitive content monitoring: websites → editorial sources → articles → keywords.
-- Owned brand identity is derived from projects (never from competitor rows).
-- Does NOT reuse project_site_pages (owned RAG/internal-link catalogue).
-- Idempotent: safe if partially applied.

-- ---------------------------------------------------------------------------
-- 1) Websites (owned + competitor)
-- ---------------------------------------------------------------------------

create table if not exists public.project_competitive_websites (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  entity_type text not null,
  competitor_id bigint null references public.project_competitors(id) on delete cascade,
  root_url text not null,
  normalized_domain text not null,
  market_code text null,
  default_language_code text null,
  include_subdomains boolean not null default false,
  is_active boolean not null default true,
  last_discovered_at timestamptz null,
  last_synced_at timestamptz null,
  last_sync_status text null,
  last_sync_error text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_competitive_websites_entity_type_check check (
    entity_type in ('owned', 'competitor')
  ),
  constraint project_competitive_websites_entity_check check (
    (
      entity_type = 'owned'
      and competitor_id is null
    )
    or (
      entity_type = 'competitor'
      and competitor_id is not null
    )
  ),
  constraint project_competitive_websites_status_check check (
    last_sync_status is null
    or last_sync_status in ('queued', 'running', 'succeeded', 'failed', 'partial')
  ),
  constraint project_competitive_websites_root_url_check check (
    char_length(trim(root_url)) > 0
  ),
  constraint project_competitive_websites_domain_check check (
    char_length(trim(normalized_domain)) > 0
  )
);

create unique index if not exists project_competitive_websites_owned_domain_unique
  on public.project_competitive_websites(project_id, normalized_domain)
  where entity_type = 'owned';

create unique index if not exists project_competitive_websites_competitor_domain_unique
  on public.project_competitive_websites(competitor_id, normalized_domain)
  where entity_type = 'competitor' and competitor_id is not null;

create index if not exists idx_project_competitive_websites_project
  on public.project_competitive_websites(project_id, is_active);

create index if not exists idx_project_competitive_websites_competitor
  on public.project_competitive_websites(competitor_id)
  where competitor_id is not null;

-- ---------------------------------------------------------------------------
-- 2) Editorial / content sources
-- ---------------------------------------------------------------------------

create table if not exists public.project_competitive_content_sources (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  website_id bigint not null
    references public.project_competitive_websites(id) on delete cascade,
  entity_type text not null,
  competitor_id bigint null references public.project_competitors(id) on delete cascade,
  source_url text not null,
  normalized_source_url text not null,
  source_type text not null default 'other',
  language_code text null,
  sitemap_url text null,
  feed_url text null,
  include_paths jsonb not null default '[]'::jsonb,
  exclude_paths jsonb not null default '[]'::jsonb,
  discovery_method text not null default 'combined',
  discovery_confidence numeric(5,4) null,
  discovery_signals jsonb not null default '[]'::jsonb,
  status text not null default 'suggested',
  is_manual_override boolean not null default false,
  last_discovered_at timestamptz null,
  last_synced_at timestamptz null,
  last_sync_status text null,
  last_sync_error text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_competitive_content_sources_entity_type_check check (
    entity_type in ('owned', 'competitor')
  ),
  constraint project_competitive_content_sources_entity_check check (
    (
      entity_type = 'owned'
      and competitor_id is null
    )
    or (
      entity_type = 'competitor'
      and competitor_id is not null
    )
  ),
  constraint project_competitive_content_sources_type_check check (
    source_type in (
      'blog', 'news', 'insights', 'resources', 'media_centre',
      'research', 'stories', 'knowledge', 'other'
    )
  ),
  constraint project_competitive_content_sources_discovery_method_check check (
    discovery_method in (
      'sitemap', 'feed', 'structured_data', 'url_pattern',
      'firecrawl_map', 'ai', 'manual', 'combined'
    )
  ),
  constraint project_competitive_content_sources_status_check check (
    status in ('suggested', 'confirmed', 'ignored', 'inactive')
  ),
  constraint project_competitive_content_sources_sync_status_check check (
    last_sync_status is null
    or last_sync_status in ('queued', 'running', 'succeeded', 'failed', 'partial')
  ),
  constraint project_competitive_content_sources_paths_array_check check (
    jsonb_typeof(include_paths) = 'array'
    and jsonb_typeof(exclude_paths) = 'array'
  ),
  constraint project_competitive_content_sources_signals_array_check check (
    jsonb_typeof(discovery_signals) = 'array'
  ),
  constraint project_competitive_content_sources_unique_url
    unique (website_id, normalized_source_url)
);

create index if not exists idx_project_competitive_content_sources_project
  on public.project_competitive_content_sources(project_id, status);

create index if not exists idx_project_competitive_content_sources_website
  on public.project_competitive_content_sources(website_id, status);

create index if not exists idx_project_competitive_content_sources_sync
  on public.project_competitive_content_sources(status, is_manual_override, last_synced_at)
  where status = 'confirmed';

-- ---------------------------------------------------------------------------
-- 3) Articles
-- ---------------------------------------------------------------------------

create table if not exists public.project_competitive_content_articles (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  website_id bigint not null
    references public.project_competitive_websites(id) on delete cascade,
  content_source_id bigint null
    references public.project_competitive_content_sources(id) on delete set null,
  entity_type text not null,
  competitor_id bigint null references public.project_competitors(id) on delete cascade,
  url text not null,
  canonical_url text not null,
  title text null,
  description text null,
  author text null,
  language_code text null,
  published_at timestamptz null,
  modified_at timestamptz null,
  image_url text null,
  page_type text null,
  summary text null,
  content_markdown text null,
  markdown_excerpt text null,
  content_hash text null,
  schema_types jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  raw_payload jsonb not null default '{}'::jsonb,
  translation_group_id uuid null,
  primary_keyword text null,
  is_active boolean not null default true,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  scraped_at timestamptz null,
  keywords_extracted_at timestamptz null,
  ranking_synced_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_competitive_content_articles_entity_type_check check (
    entity_type in ('owned', 'competitor')
  ),
  constraint project_competitive_content_articles_entity_check check (
    (
      entity_type = 'owned'
      and competitor_id is null
    )
    or (
      entity_type = 'competitor'
      and competitor_id is not null
    )
  ),
  constraint project_competitive_content_articles_schema_array_check check (
    jsonb_typeof(schema_types) = 'array'
  ),
  constraint project_competitive_content_articles_unique_canonical
    unique (project_id, entity_type, canonical_url)
);

create index if not exists idx_project_competitive_articles_project_published
  on public.project_competitive_content_articles(project_id, published_at desc nulls last);

create index if not exists idx_project_competitive_articles_entity_published
  on public.project_competitive_content_articles(
    project_id, entity_type, competitor_id, published_at desc nulls last
  );

create index if not exists idx_project_competitive_articles_source
  on public.project_competitive_content_articles(content_source_id, published_at desc nulls last)
  where content_source_id is not null;

create index if not exists idx_project_competitive_articles_language
  on public.project_competitive_content_articles(project_id, language_code)
  where language_code is not null;

create index if not exists idx_project_competitive_articles_active
  on public.project_competitive_content_articles(project_id, is_active)
  where is_active = true;

create index if not exists idx_project_competitive_articles_translation
  on public.project_competitive_content_articles(translation_group_id)
  where translation_group_id is not null;

create index if not exists idx_project_competitive_articles_primary_kw
  on public.project_competitive_content_articles(project_id, primary_keyword)
  where primary_keyword is not null;

-- ---------------------------------------------------------------------------
-- 4) Article keywords
-- ---------------------------------------------------------------------------

create table if not exists public.project_competitive_article_keywords (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  article_id bigint not null
    references public.project_competitive_content_articles(id) on delete cascade,
  entity_type text not null,
  competitor_id bigint null references public.project_competitors(id) on delete cascade,
  keyword text not null,
  normalized_keyword text not null,
  keyword_type text not null,
  source text not null,
  language_code text null,
  location_code text null,
  confidence numeric(5,4) null,
  search_volume integer null,
  competition numeric null,
  cpc numeric null,
  ranking_position numeric null,
  ranking_url text null,
  clicks integer null,
  impressions integer null,
  ctr numeric null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_competitive_article_keywords_entity_type_check check (
    entity_type in ('owned', 'competitor')
  ),
  constraint project_competitive_article_keywords_type_check check (
    keyword_type in (
      'inferred_primary', 'inferred_secondary', 'ranking', 'search_console_query'
    )
  ),
  constraint project_competitive_article_keywords_source_check check (
    source in (
      'keyword_research', 'content_analysis', 'dataforseo',
      'search_console', 'manual'
    )
  ),
  constraint project_competitive_article_keywords_keyword_check check (
    char_length(trim(keyword)) > 0
  )
);

create unique index if not exists project_competitive_article_keywords_unique
  on public.project_competitive_article_keywords(
    article_id,
    normalized_keyword,
    keyword_type,
    source,
    coalesce(language_code, ''),
    coalesce(location_code, '')
  );

create index if not exists idx_project_competitive_article_keywords_project
  on public.project_competitive_article_keywords(project_id, keyword_type);

create index if not exists idx_project_competitive_article_keywords_keyword
  on public.project_competitive_article_keywords(project_id, normalized_keyword);

create index if not exists idx_project_competitive_article_keywords_article
  on public.project_competitive_article_keywords(article_id, keyword_type);

-- ---------------------------------------------------------------------------
-- 5) Sync runs
-- ---------------------------------------------------------------------------

create table if not exists public.project_competitive_content_sync_runs (
  id uuid primary key default gen_random_uuid(),
  project_id integer null references public.projects(id) on delete cascade,
  entity_type text null,
  competitor_id bigint null references public.project_competitors(id) on delete set null,
  website_id bigint null
    references public.project_competitive_websites(id) on delete set null,
  content_source_id bigint null
    references public.project_competitive_content_sources(id) on delete set null,
  run_type text not null,
  trigger_type text not null,
  provider text null,
  status text not null default 'queued',
  started_at timestamptz null,
  completed_at timestamptz null,
  discovered_count integer not null default 0,
  created_count integer not null default 0,
  updated_count integer not null default 0,
  skipped_count integer not null default 0,
  error_code text null,
  error_message text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_competitive_content_sync_runs_run_type_check check (
    run_type in (
      'source_discovery', 'article_sync', 'keyword_extraction',
      'keyword_rank_sync', 'search_console_sync', 'analytics_sync'
    )
  ),
  constraint project_competitive_content_sync_runs_trigger_check check (
    trigger_type in ('manual', 'scheduled', 'initial', 'retry', 'automatic')
  ),
  constraint project_competitive_content_sync_runs_status_check check (
    status in ('queued', 'running', 'succeeded', 'failed', 'partial')
  ),
  constraint project_competitive_content_sync_runs_entity_type_check check (
    entity_type is null or entity_type in ('owned', 'competitor')
  )
);

create index if not exists idx_project_competitive_content_sync_runs_project
  on public.project_competitive_content_sync_runs(project_id, created_at desc);

create index if not exists idx_project_competitive_content_sync_runs_type
  on public.project_competitive_content_sync_runs(run_type, status, created_at desc);

-- ---------------------------------------------------------------------------
-- 6) Google Search Console (owned only)
-- ---------------------------------------------------------------------------

create table if not exists public.project_search_console_properties (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  website_id bigint null
    references public.project_competitive_websites(id) on delete set null,
  provider text not null default 'google_search_console',
  property_url text not null,
  site_type text null,
  is_active boolean not null default true,
  granted_scopes jsonb not null default '[]'::jsonb,
  last_synced_at timestamptz null,
  last_sync_status text null,
  last_sync_error text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_search_console_properties_provider_check check (
    provider = 'google_search_console'
  ),
  constraint project_search_console_properties_status_check check (
    last_sync_status is null
    or last_sync_status in ('queued', 'running', 'succeeded', 'failed', 'partial')
  ),
  constraint project_search_console_properties_unique_property
    unique (project_id, property_url)
);

create index if not exists idx_project_search_console_properties_project
  on public.project_search_console_properties(project_id, is_active);

create table if not exists public.project_search_console_page_query_daily (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  property_id bigint not null
    references public.project_search_console_properties(id) on delete cascade,
  article_id bigint null
    references public.project_competitive_content_articles(id) on delete set null,
  metric_date date not null,
  page_url text not null,
  canonical_url text null,
  query text not null,
  clicks integer null,
  impressions integer null,
  ctr numeric null,
  position numeric null,
  country text null,
  device text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists project_search_console_page_query_daily_unique
  on public.project_search_console_page_query_daily(
    property_id,
    metric_date,
    page_url,
    query,
    coalesce(country, ''),
    coalesce(device, '')
  );

create index if not exists idx_project_search_console_daily_project_date
  on public.project_search_console_page_query_daily(project_id, metric_date desc);

create index if not exists idx_project_search_console_daily_article
  on public.project_search_console_page_query_daily(article_id, metric_date desc)
  where article_id is not null;

create index if not exists idx_project_search_console_daily_page
  on public.project_search_console_page_query_daily(project_id, canonical_url)
  where canonical_url is not null;

-- ---------------------------------------------------------------------------
-- 7) Runtime settings
-- ---------------------------------------------------------------------------

insert into public.app_runtime_settings (key, value)
values (
  'competitive_content_sync',
  jsonb_build_object(
    'daily_cron_hour_utc', 7,
    'weekly_cron_dow', 1,
    'weekly_cron_hour_utc', 8,
    'monthly_discovery_day', 1,
    'monthly_discovery_hour_utc', 9,
    'first_sync_days', 90,
    'max_articles_per_source', 100,
    'ai_confidence_low', 0.35,
    'ai_confidence_high', 0.75
  )
)
on conflict (key) do nothing;

-- ---------------------------------------------------------------------------
-- 8) RLS
-- ---------------------------------------------------------------------------

alter table public.project_competitive_websites enable row level security;
alter table public.project_competitive_content_sources enable row level security;
alter table public.project_competitive_content_articles enable row level security;
alter table public.project_competitive_article_keywords enable row level security;
alter table public.project_competitive_content_sync_runs enable row level security;
alter table public.project_search_console_properties enable row level security;
alter table public.project_search_console_page_query_daily enable row level security;

-- Websites: full CRUD for editors
drop policy if exists project_competitive_websites_select on public.project_competitive_websites;
create policy project_competitive_websites_select
  on public.project_competitive_websites for select to authenticated
  using (public.can_edit_project(project_id));

drop policy if exists project_competitive_websites_insert on public.project_competitive_websites;
create policy project_competitive_websites_insert
  on public.project_competitive_websites for insert to authenticated
  with check (public.can_edit_project(project_id));

drop policy if exists project_competitive_websites_update on public.project_competitive_websites;
create policy project_competitive_websites_update
  on public.project_competitive_websites for update to authenticated
  using (public.can_edit_project(project_id))
  with check (public.can_edit_project(project_id));

drop policy if exists project_competitive_websites_delete on public.project_competitive_websites;
create policy project_competitive_websites_delete
  on public.project_competitive_websites for delete to authenticated
  using (public.can_edit_project(project_id));

-- Sources: full CRUD for editors (confirm/ignore/manual)
drop policy if exists project_competitive_content_sources_select
  on public.project_competitive_content_sources;
create policy project_competitive_content_sources_select
  on public.project_competitive_content_sources for select to authenticated
  using (public.can_edit_project(project_id));

drop policy if exists project_competitive_content_sources_insert
  on public.project_competitive_content_sources;
create policy project_competitive_content_sources_insert
  on public.project_competitive_content_sources for insert to authenticated
  with check (public.can_edit_project(project_id));

drop policy if exists project_competitive_content_sources_update
  on public.project_competitive_content_sources;
create policy project_competitive_content_sources_update
  on public.project_competitive_content_sources for update to authenticated
  using (public.can_edit_project(project_id))
  with check (public.can_edit_project(project_id));

drop policy if exists project_competitive_content_sources_delete
  on public.project_competitive_content_sources;
create policy project_competitive_content_sources_delete
  on public.project_competitive_content_sources for delete to authenticated
  using (public.can_edit_project(project_id));

-- Articles / keywords / sync runs / GSC daily: select-only for authenticated
drop policy if exists project_competitive_content_articles_select
  on public.project_competitive_content_articles;
create policy project_competitive_content_articles_select
  on public.project_competitive_content_articles for select to authenticated
  using (public.can_edit_project(project_id));

revoke insert, update, delete on public.project_competitive_content_articles from authenticated;

drop policy if exists project_competitive_article_keywords_select
  on public.project_competitive_article_keywords;
create policy project_competitive_article_keywords_select
  on public.project_competitive_article_keywords for select to authenticated
  using (public.can_edit_project(project_id));

revoke insert, update, delete on public.project_competitive_article_keywords from authenticated;

drop policy if exists project_competitive_content_sync_runs_select
  on public.project_competitive_content_sync_runs;
create policy project_competitive_content_sync_runs_select
  on public.project_competitive_content_sync_runs for select to authenticated
  using (project_id is not null and public.can_edit_project(project_id));

revoke insert, update, delete on public.project_competitive_content_sync_runs from authenticated;

-- GSC properties: editors can configure
drop policy if exists project_search_console_properties_select
  on public.project_search_console_properties;
create policy project_search_console_properties_select
  on public.project_search_console_properties for select to authenticated
  using (public.can_edit_project(project_id));

drop policy if exists project_search_console_properties_insert
  on public.project_search_console_properties;
create policy project_search_console_properties_insert
  on public.project_search_console_properties for insert to authenticated
  with check (public.can_edit_project(project_id));

drop policy if exists project_search_console_properties_update
  on public.project_search_console_properties;
create policy project_search_console_properties_update
  on public.project_search_console_properties for update to authenticated
  using (public.can_edit_project(project_id))
  with check (public.can_edit_project(project_id));

drop policy if exists project_search_console_properties_delete
  on public.project_search_console_properties;
create policy project_search_console_properties_delete
  on public.project_search_console_properties for delete to authenticated
  using (public.can_edit_project(project_id));

drop policy if exists project_search_console_page_query_daily_select
  on public.project_search_console_page_query_daily;
create policy project_search_console_page_query_daily_select
  on public.project_search_console_page_query_daily for select to authenticated
  using (public.can_edit_project(project_id));

revoke insert, update, delete on public.project_search_console_page_query_daily from authenticated;

grant select, insert, update, delete on public.project_competitive_websites to authenticated;
grant select, insert, update, delete on public.project_competitive_content_sources to authenticated;
grant select on public.project_competitive_content_articles to authenticated;
grant select on public.project_competitive_article_keywords to authenticated;
grant select on public.project_competitive_content_sync_runs to authenticated;
grant select, insert, update, delete on public.project_search_console_properties to authenticated;
grant select on public.project_search_console_page_query_daily to authenticated;

-- ---------------------------------------------------------------------------
-- 9) Unified views
-- ---------------------------------------------------------------------------

create or replace view public.v_project_competitive_content_entities
with (security_invoker = true)
as
select
  p.id as project_id,
  ('owned:' || p.id::text) as entity_id,
  coalesce(nullif(trim(p.name), ''), 'Our brand') as entity_name,
  'owned'::text as entity_type,
  true as is_owned,
  null::bigint as competitor_id
from public.projects p
where coalesce(p.is_deleted, false) = false
  and coalesce(p.active, true) = true

union all

select
  c.project_id,
  ('competitor:' || c.id::text) as entity_id,
  c.name as entity_name,
  'competitor'::text as entity_type,
  false as is_owned,
  c.id as competitor_id
from public.project_competitors c
where c.is_active = true;

create or replace view public.v_project_competitive_content_articles
with (security_invoker = true)
as
select
  a.id,
  a.project_id,
  a.website_id,
  a.content_source_id,
  a.entity_type,
  a.competitor_id,
  case
    when a.entity_type = 'owned' then ('owned:' || a.project_id::text)
    else ('competitor:' || a.competitor_id::text)
  end as entity_id,
  case
    when a.entity_type = 'owned' then coalesce(nullif(trim(p.name), ''), 'Our brand')
    else c.name
  end as entity_name,
  (a.entity_type = 'owned') as is_owned,
  a.url,
  a.canonical_url,
  a.title,
  a.description,
  a.author,
  a.language_code,
  a.published_at,
  a.modified_at,
  a.image_url,
  a.page_type,
  a.summary,
  a.markdown_excerpt,
  a.content_hash,
  a.schema_types,
  a.translation_group_id,
  a.primary_keyword,
  a.is_active,
  a.first_seen_at,
  a.last_seen_at,
  a.scraped_at,
  a.keywords_extracted_at,
  a.ranking_synced_at,
  a.created_at,
  a.updated_at,
  s.source_url as content_source_url,
  s.source_type as content_source_type,
  s.language_code as content_source_language,
  w.root_url as website_root_url,
  w.normalized_domain as website_domain
from public.project_competitive_content_articles a
join public.projects p on p.id = a.project_id
left join public.project_competitors c on c.id = a.competitor_id
left join public.project_competitive_content_sources s on s.id = a.content_source_id
left join public.project_competitive_websites w on w.id = a.website_id;

-- ---------------------------------------------------------------------------
-- 10) RPCs
-- ---------------------------------------------------------------------------

create or replace function public.fn_list_project_competitive_articles(
  p_project_id integer,
  p_date_from timestamptz default null,
  p_date_to timestamptz default null,
  p_entity_ids text[] default null,
  p_language_codes text[] default null,
  p_source_types text[] default null,
  p_keywords text[] default null,
  p_has_ranking boolean default null,
  p_limit integer default 100,
  p_offset integer default 0
)
returns setof public.v_project_competitive_content_articles
language plpgsql
stable
security invoker
set search_path to 'pg_catalog', 'public'
as $$
begin
  if p_project_id is null or not public.can_edit_project(p_project_id) then
    raise exception 'forbidden';
  end if;

  return query
  select v.*
  from public.v_project_competitive_content_articles v
  where v.project_id = p_project_id
    and v.is_active = true
    and (p_date_from is null or v.published_at >= p_date_from or (v.published_at is null and v.first_seen_at >= p_date_from))
    and (p_date_to is null or v.published_at <= p_date_to or (v.published_at is null and v.first_seen_at <= p_date_to))
    and (p_entity_ids is null or cardinality(p_entity_ids) = 0 or v.entity_id = any (p_entity_ids))
    and (p_language_codes is null or cardinality(p_language_codes) = 0 or v.language_code = any (p_language_codes))
    and (p_source_types is null or cardinality(p_source_types) = 0 or v.content_source_type = any (p_source_types))
    and (
      p_keywords is null
      or cardinality(p_keywords) = 0
      or exists (
        select 1
        from public.project_competitive_article_keywords k
        where k.article_id = v.id
          and k.normalized_keyword = any (
            select lower(trim(x)) from unnest(p_keywords) as x
          )
      )
      or lower(coalesce(v.primary_keyword, '')) = any (
        select lower(trim(x)) from unnest(p_keywords) as x
      )
    )
    and (
      p_has_ranking is null
      or (
        p_has_ranking = true
        and exists (
          select 1
          from public.project_competitive_article_keywords k
          where k.article_id = v.id
            and k.keyword_type = 'ranking'
            and k.ranking_position is not null
        )
      )
      or (
        p_has_ranking = false
        and not exists (
          select 1
          from public.project_competitive_article_keywords k
          where k.article_id = v.id
            and k.keyword_type = 'ranking'
            and k.ranking_position is not null
        )
      )
    )
  order by coalesce(v.published_at, v.first_seen_at) desc nulls last
  limit greatest(1, least(coalesce(p_limit, 100), 500))
  offset greatest(0, coalesce(p_offset, 0));
end;
$$;

revoke all on function public.fn_list_project_competitive_articles(
  integer, timestamptz, timestamptz, text[], text[], text[], text[], boolean, integer, integer
) from public;
grant execute on function public.fn_list_project_competitive_articles(
  integer, timestamptz, timestamptz, text[], text[], text[], text[], boolean, integer, integer
) to authenticated;
grant execute on function public.fn_list_project_competitive_articles(
  integer, timestamptz, timestamptz, text[], text[], text[], text[], boolean, integer, integer
) to service_role;

create or replace function public.fn_get_project_competitive_content_summary(
  p_project_id integer,
  p_date_from timestamptz default null,
  p_date_to timestamptz default null,
  p_entity_ids text[] default null,
  p_language_codes text[] default null,
  p_source_types text[] default null
)
returns jsonb
language plpgsql
stable
security invoker
set search_path to 'pg_catalog', 'public'
as $$
declare
  v_result jsonb;
  v_days numeric;
begin
  if p_project_id is null or not public.can_edit_project(p_project_id) then
    raise exception 'forbidden';
  end if;

  v_days := greatest(
    1,
    extract(epoch from (coalesce(p_date_to, now()) - coalesce(p_date_from, now() - interval '30 days'))) / 86400.0
  );

  with entities as (
    select *
    from public.v_project_competitive_content_entities e
    where e.project_id = p_project_id
      and (p_entity_ids is null or cardinality(p_entity_ids) = 0 or e.entity_id = any (p_entity_ids))
  ),
  filtered as (
    select v.*
    from public.v_project_competitive_content_articles v
    where v.project_id = p_project_id
      and v.is_active = true
      and (p_date_from is null or coalesce(v.published_at, v.first_seen_at) >= p_date_from)
      and (p_date_to is null or coalesce(v.published_at, v.first_seen_at) <= p_date_to)
      and (p_entity_ids is null or cardinality(p_entity_ids) = 0 or v.entity_id = any (p_entity_ids))
      and (p_language_codes is null or cardinality(p_language_codes) = 0 or v.language_code = any (p_language_codes))
      and (p_source_types is null or cardinality(p_source_types) = 0 or v.content_source_type = any (p_source_types))
  ),
  entity_stats as (
    select
      e.entity_id,
      e.entity_name,
      e.entity_type,
      e.is_owned,
      count(f.id)::integer as articles_count,
      count(distinct f.language_code) filter (where f.language_code is not null)::integer as languages_count,
      count(distinct f.content_source_id) filter (where f.content_source_id is not null)::integer as sources_count,
      max(coalesce(f.published_at, f.first_seen_at)) as last_published_at,
      (
        select count(distinct k.normalized_keyword)::integer
        from public.project_competitive_article_keywords k
        join filtered f2 on f2.id = k.article_id
        where f2.entity_id = e.entity_id
          and k.keyword_type in ('inferred_primary', 'inferred_secondary')
      ) as unique_keywords,
      (
        select coalesce(sum(k.search_volume), 0)::bigint
        from public.project_competitive_article_keywords k
        join filtered f2 on f2.id = k.article_id
        where f2.entity_id = e.entity_id
          and k.keyword_type = 'inferred_primary'
          and k.search_volume is not null
      ) as keyword_volume_total,
      (
        select count(*)::integer
        from public.project_competitive_article_keywords k
        join filtered f2 on f2.id = k.article_id
        where f2.entity_id = e.entity_id
          and k.keyword_type = 'ranking'
          and k.ranking_position is not null
      ) as ranking_keywords_count,
      (
        select avg(k.ranking_position)
        from public.project_competitive_article_keywords k
        join filtered f2 on f2.id = k.article_id
        where f2.entity_id = e.entity_id
          and k.keyword_type = 'ranking'
          and k.ranking_position is not null
      ) as ranking_position_avg
    from entities e
    left join filtered f on f.entity_id = e.entity_id
    group by e.entity_id, e.entity_name, e.entity_type, e.is_owned
  ),
  language_dist as (
    select
      f.entity_id,
      jsonb_object_agg(coalesce(f.language_code, 'unknown'), cnt) as by_language
    from (
      select entity_id, language_code, count(*)::integer as cnt
      from filtered
      group by entity_id, language_code
    ) f
    group by f.entity_id
  ),
  source_dist as (
    select
      f.entity_id,
      jsonb_object_agg(coalesce(f.content_source_type, 'other'), cnt) as by_source_type
    from (
      select entity_id, content_source_type, count(*)::integer as cnt
      from filtered
      group by entity_id, content_source_type
    ) f
    group by f.entity_id
  ),
  weekly as (
    select
      f.entity_id,
      date_trunc('week', coalesce(f.published_at, f.first_seen_at))::date as week_start,
      count(*)::integer as articles_count
    from filtered f
    where coalesce(f.published_at, f.first_seen_at) is not null
    group by f.entity_id, date_trunc('week', coalesce(f.published_at, f.first_seen_at))
  ),
  weekly_agg as (
    select
      entity_id,
      jsonb_agg(
        jsonb_build_object('week_start', week_start, 'articles_count', articles_count)
        order by week_start
      ) as series
    from weekly
    group by entity_id
  ),
  top_articles as (
    select
      x.entity_id,
      jsonb_agg(
        jsonb_build_object(
          'id', x.id,
          'title', x.title,
          'url', x.url,
          'published_at', x.published_at,
          'primary_keyword', x.primary_keyword,
          'image_url', x.image_url
        )
        order by coalesce(x.published_at, x.first_seen_at) desc nulls last
      ) as articles
    from (
      select
        f.*,
        row_number() over (
          partition by f.entity_id
          order by coalesce(f.published_at, f.first_seen_at) desc nulls last
        ) as rn
      from filtered f
    ) x
    where x.rn <= 5
    group by x.entity_id
  ),
  totals as (
    select
      coalesce(sum(articles_count), 0)::integer as articles_count,
      count(*)::integer as entities_count
    from entity_stats
  )
  select jsonb_build_object(
    'project_id', p_project_id,
    'date_from', p_date_from,
    'date_to', p_date_to,
    'period_days', v_days,
    'totals', jsonb_build_object(
      'articles_count', t.articles_count,
      'entities_count', t.entities_count
    ),
    'entities', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'entity_id', es.entity_id,
          'entity_name', es.entity_name,
          'entity_type', es.entity_type,
          'is_owned', es.is_owned,
          'articles_count', es.articles_count,
          'articles_per_week', case
            when es.articles_count = 0 then 0
            else round((es.articles_count::numeric / (v_days / 7.0))::numeric, 2)
          end,
          'articles_per_month', case
            when es.articles_count = 0 then 0
            else round((es.articles_count::numeric / (v_days / 30.0))::numeric, 2)
          end,
          'days_since_last_publish', case
            when es.last_published_at is null then null
            else floor(extract(epoch from (now() - es.last_published_at)) / 86400.0)::integer
          end,
          'languages_count', es.languages_count,
          'sources_count', es.sources_count,
          'unique_keywords', coalesce(es.unique_keywords, 0),
          'keyword_volume_total', es.keyword_volume_total,
          'ranking_keywords_count', coalesce(es.ranking_keywords_count, 0),
          'ranking_position_avg', es.ranking_position_avg,
          'share_of_articles_pct', case
            when t.articles_count = 0 then null
            else round((es.articles_count::numeric * 100.0 / t.articles_count)::numeric, 1)
          end,
          'by_language', coalesce(ld.by_language, '{}'::jsonb),
          'by_source_type', coalesce(sd.by_source_type, '{}'::jsonb),
          'weekly_series', coalesce(wa.series, '[]'::jsonb),
          'top_articles', coalesce(ta.articles, '[]'::jsonb)
        )
        order by es.is_owned desc, es.articles_count desc, es.entity_name
      )
      from entity_stats es
      left join language_dist ld on ld.entity_id = es.entity_id
      left join source_dist sd on sd.entity_id = es.entity_id
      left join weekly_agg wa on wa.entity_id = es.entity_id
      left join top_articles ta on ta.entity_id = es.entity_id
    ), '[]'::jsonb)
  )
  into v_result
  from totals t;

  return v_result;
end;
$$;

revoke all on function public.fn_get_project_competitive_content_summary(
  integer, timestamptz, timestamptz, text[], text[], text[]
) from public;
grant execute on function public.fn_get_project_competitive_content_summary(
  integer, timestamptz, timestamptz, text[], text[], text[]
) to authenticated;
grant execute on function public.fn_get_project_competitive_content_summary(
  integer, timestamptz, timestamptz, text[], text[], text[]
) to service_role;

create or replace function public.fn_get_project_keyword_gap(
  p_project_id integer,
  p_date_from timestamptz default null,
  p_date_to timestamptz default null,
  p_min_volume integer default 10
)
returns jsonb
language plpgsql
stable
security invoker
set search_path to 'pg_catalog', 'public'
as $$
begin
  if p_project_id is null or not public.can_edit_project(p_project_id) then
    raise exception 'forbidden';
  end if;

  return (
    with article_scope as (
      select a.id, a.entity_type, a.competitor_id
      from public.project_competitive_content_articles a
      where a.project_id = p_project_id
        and a.is_active = true
        and (p_date_from is null or coalesce(a.published_at, a.first_seen_at) >= p_date_from)
        and (p_date_to is null or coalesce(a.published_at, a.first_seen_at) <= p_date_to)
    ),
    keyword_rows as (
      select
        k.normalized_keyword,
        k.keyword,
        k.search_volume,
        k.ranking_position,
        k.entity_type,
        k.article_id,
        a.competitor_id
      from public.project_competitive_article_keywords k
      join article_scope a on a.id = k.article_id
      where k.keyword_type in ('inferred_primary', 'inferred_secondary', 'ranking')
    ),
    by_keyword as (
      select
        normalized_keyword,
        max(keyword) as keyword,
        max(search_volume) filter (where search_volume is not null) as search_volume,
        count(distinct competitor_id) filter (where entity_type = 'competitor')::integer as competitors_count,
        count(*) filter (where entity_type = 'competitor')::integer as competitor_articles_count,
        min(ranking_position) filter (
          where entity_type = 'competitor' and ranking_position is not null
        ) as best_competitor_position,
        count(*) filter (where entity_type = 'owned')::integer as owned_articles_count,
        min(ranking_position) filter (
          where entity_type = 'owned' and ranking_position is not null
        ) as owned_ranking_position
      from keyword_rows
      group by normalized_keyword
    )
    select coalesce(jsonb_agg(
      jsonb_build_object(
        'keyword', keyword,
        'normalized_keyword', normalized_keyword,
        'search_volume', search_volume,
        'competitors_count', competitors_count,
        'competitor_articles_count', competitor_articles_count,
        'best_competitor_position', best_competitor_position,
        'owned_articles_count', owned_articles_count,
        'owned_ranking_position', owned_ranking_position,
        'opportunity_status', case
          when competitors_count = 0 and owned_articles_count = 0 then 'insufficient_data'
          when owned_articles_count = 0 and competitors_count > 0 then 'not_covered'
          when owned_articles_count > 0 and owned_ranking_position is null
            and best_competitor_position is not null then 'covered_not_ranking'
          when owned_ranking_position is not null
            and best_competitor_position is not null
            and owned_ranking_position > best_competitor_position then 'ranking_below_competitors'
          when owned_ranking_position is not null
            and (
              best_competitor_position is null
              or owned_ranking_position <= best_competitor_position
            ) then 'owned_advantage'
          else 'insufficient_data'
        end
      )
      order by coalesce(search_volume, 0) desc, competitors_count desc, keyword
    ), '[]'::jsonb)
    from by_keyword
    where competitors_count > 0
      and (search_volume is null or search_volume >= coalesce(p_min_volume, 10))
  );
end;
$$;

revoke all on function public.fn_get_project_keyword_gap(integer, timestamptz, timestamptz, integer) from public;
grant execute on function public.fn_get_project_keyword_gap(integer, timestamptz, timestamptz, integer) to authenticated;
grant execute on function public.fn_get_project_keyword_gap(integer, timestamptz, timestamptz, integer) to service_role;

create or replace function public.fn_get_owned_content_performance(
  p_project_id integer,
  p_date_from date default null,
  p_date_to date default null
)
returns jsonb
language plpgsql
stable
security invoker
set search_path to 'pg_catalog', 'public'
as $$
declare
  v_gsc_connected boolean;
  v_ga_connected boolean;
  v_gsc jsonb;
  v_ga jsonb;
begin
  if p_project_id is null or not public.can_edit_project(p_project_id) then
    raise exception 'forbidden';
  end if;

  select exists (
    select 1
    from public.project_search_console_properties p
    where p.project_id = p_project_id and p.is_active = true
  ) into v_gsc_connected;

  v_ga_connected := to_regclass('public.project_analytics_properties') is not null
    and exists (
      select 1
      from public.project_analytics_properties p
      where p.project_id = p_project_id and p.is_active = true
    );

  if v_gsc_connected then
    select jsonb_build_object(
      'clicks', sum(clicks),
      'impressions', sum(impressions),
      'ctr', case
        when coalesce(sum(impressions), 0) = 0 then null
        else sum(clicks)::numeric / nullif(sum(impressions), 0)
      end,
      'position_avg', avg(position)
    )
    into v_gsc
    from public.project_search_console_page_query_daily d
    where d.project_id = p_project_id
      and (p_date_from is null or d.metric_date >= p_date_from)
      and (p_date_to is null or d.metric_date <= p_date_to);
  else
    v_gsc := null;
  end if;

  if v_ga_connected and to_regclass('public.project_analytics_pages_daily') is not null then
    begin
      execute $q$
        select jsonb_build_object(
          'page_views', sum(page_views),
          'users', sum(users),
          'sessions', sum(sessions),
          'engaged_sessions', sum(engaged_sessions),
          'engagement_rate', avg(engagement_rate)
        )
        from public.project_analytics_pages_daily d
        where d.project_id = $1
          and ($2::date is null or d.metric_date >= $2)
          and ($3::date is null or d.metric_date <= $3)
      $q$
      into v_ga
      using p_project_id, p_date_from, p_date_to;
    exception
      when undefined_column then
        -- Column names may differ across analytics schema revisions.
        v_ga := jsonb_build_object('note', 'analytics_pages_schema_mismatch');
      when others then
        v_ga := null;
    end;
  else
    v_ga := null;
  end if;

  return jsonb_build_object(
    'project_id', p_project_id,
    'date_from', p_date_from,
    'date_to', p_date_to,
    'search_console_connected', v_gsc_connected,
    'analytics_connected', v_ga_connected,
    'search_console', v_gsc,
    'analytics', v_ga
  );
end;
$$;

revoke all on function public.fn_get_owned_content_performance(integer, date, date) from public;
grant execute on function public.fn_get_owned_content_performance(integer, date, date) to authenticated;
grant execute on function public.fn_get_owned_content_performance(integer, date, date) to service_role;
