-- Prompt research saved lists (separate from keyword_lists / project_ai_prompts).

CREATE TABLE IF NOT EXISTS public.prompt_lists (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  notes text NULL,
  created_by integer NOT NULL DEFAULT public.current_user_id() REFERENCES public.users (id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.prompt_list_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  list_id bigint NOT NULL REFERENCES public.prompt_lists (id) ON DELETE CASCADE,
  prompt text NOT NULL,
  language_code text NULL,
  region_id text NULL,
  notes text NULL,
  added_by integer NOT NULL DEFAULT public.current_user_id() REFERENCES public.users (id),
  added_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS prompt_lists_created_by_created_at_idx
  ON public.prompt_lists (created_by, created_at DESC);

CREATE INDEX IF NOT EXISTS prompt_list_items_list_id_added_at_idx
  ON public.prompt_list_items (list_id, added_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS prompt_list_items_list_prompt_unique_idx
  ON public.prompt_list_items (list_id, lower(btrim(prompt)));

DROP TRIGGER IF EXISTS prompt_lists_set_updated_at ON public.prompt_lists;
CREATE TRIGGER prompt_lists_set_updated_at
  BEFORE UPDATE ON public.prompt_lists
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS prompt_list_items_set_updated_at ON public.prompt_list_items;
CREATE TRIGGER prompt_list_items_set_updated_at
  BEFORE UPDATE ON public.prompt_list_items
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.prompt_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prompt_list_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "read own prompt lists" ON public.prompt_lists;
CREATE POLICY "read own prompt lists"
  ON public.prompt_lists
  FOR SELECT
  USING (created_by = public.current_user_id());

DROP POLICY IF EXISTS "create own prompt lists" ON public.prompt_lists;
CREATE POLICY "create own prompt lists"
  ON public.prompt_lists
  FOR INSERT
  WITH CHECK (true);

DROP POLICY IF EXISTS "update own prompt lists" ON public.prompt_lists;
CREATE POLICY "update own prompt lists"
  ON public.prompt_lists
  FOR UPDATE
  USING (created_by = public.current_user_id())
  WITH CHECK (created_by = public.current_user_id());

DROP POLICY IF EXISTS "delete own prompt lists" ON public.prompt_lists;
CREATE POLICY "delete own prompt lists"
  ON public.prompt_lists
  FOR DELETE
  USING (created_by = public.current_user_id());

DROP POLICY IF EXISTS "read prompts in own lists" ON public.prompt_list_items;
CREATE POLICY "read prompts in own lists"
  ON public.prompt_list_items
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1
      FROM public.prompt_lists l
      WHERE l.id = prompt_list_items.list_id
        AND l.created_by = public.current_user_id()
    )
  );

DROP POLICY IF EXISTS "insert prompts into own lists" ON public.prompt_list_items;
CREATE POLICY "insert prompts into own lists"
  ON public.prompt_list_items
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.prompt_lists l
      WHERE l.id = prompt_list_items.list_id
        AND l.created_by = public.current_user_id()
    )
  );

DROP POLICY IF EXISTS "update prompts in own lists" ON public.prompt_list_items;
CREATE POLICY "update prompts in own lists"
  ON public.prompt_list_items
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1
      FROM public.prompt_lists l
      WHERE l.id = prompt_list_items.list_id
        AND l.created_by = public.current_user_id()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.prompt_lists l
      WHERE l.id = prompt_list_items.list_id
        AND l.created_by = public.current_user_id()
    )
  );

DROP POLICY IF EXISTS "delete prompts in own lists" ON public.prompt_list_items;
CREATE POLICY "delete prompts in own lists"
  ON public.prompt_list_items
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1
      FROM public.prompt_lists l
      WHERE l.id = prompt_list_items.list_id
        AND l.created_by = public.current_user_id()
    )
  );

GRANT SELECT, INSERT, UPDATE, DELETE ON public.prompt_lists TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.prompt_list_items TO authenticated;
GRANT ALL ON public.prompt_lists TO service_role;
GRANT ALL ON public.prompt_list_items TO service_role;
