-- Per-project Google OAuth connections for Search Console + Analytics (user one-click connect).
-- Refresh tokens are service-role only; clients read status via token-free RPCs.

create table if not exists public.project_google_oauth_connections (
  id bigint generated by default as identity primary key,
  project_id integer not null references public.projects(id) on delete cascade,
  google_account_email text null,
  google_account_sub text null,
  refresh_token text not null,
  access_token text null,
  access_token_expires_at timestamptz null,
  scopes text[] not null default '{}'::text[],
  status text not null default 'active',
  connected_by_auth_user_id uuid null,
  last_error text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_google_oauth_connections_project_unique unique (project_id),
  constraint project_google_oauth_connections_status_check check (
    status in ('active', 'revoked', 'error')
  )
);

create index if not exists idx_project_google_oauth_connections_status
  on public.project_google_oauth_connections(status)
  where status = 'active';

comment on table public.project_google_oauth_connections is
  'Per-project Google OAuth refresh tokens for Search Console and Analytics. Service-role only.';

alter table public.project_google_oauth_connections enable row level security;

revoke all on table public.project_google_oauth_connections from anon, authenticated;
grant all on table public.project_google_oauth_connections to service_role;

create or replace function public.fn_can_edit_project_check(p_project_id integer)
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select coalesce(public.can_edit_project(p_project_id), false);
$$;

grant execute on function public.fn_can_edit_project_check(integer) to authenticated;

-- Token-free status for project editors (security definer; never returns refresh_token)
create or replace function public.fn_get_project_google_oauth_status(p_project_id integer)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  rec record;
begin
  if p_project_id is null or not public.can_edit_project(p_project_id) then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  select
    c.id,
    c.project_id,
    c.google_account_email,
    c.scopes,
    c.status,
    c.connected_by_auth_user_id,
    c.last_error,
    c.created_at,
    c.updated_at,
    (c.refresh_token is not null and length(c.refresh_token) > 0) as has_refresh_token
  into rec
  from public.project_google_oauth_connections c
  where c.project_id = p_project_id
    and c.status = 'active'
  order by c.updated_at desc
  limit 1;

  if not found then
    return jsonb_build_object('connected', false);
  end if;

  return jsonb_build_object(
    'connected', true,
    'id', rec.id,
    'project_id', rec.project_id,
    'google_account_email', rec.google_account_email,
    'scopes', to_jsonb(rec.scopes),
    'status', rec.status,
    'connected_by_auth_user_id', rec.connected_by_auth_user_id,
    'last_error', rec.last_error,
    'created_at', rec.created_at,
    'updated_at', rec.updated_at,
    'has_refresh_token', rec.has_refresh_token
  );
end;
$$;

grant execute on function public.fn_get_project_google_oauth_status(integer) to authenticated;

create or replace function public.fn_disconnect_project_google_oauth(p_project_id integer)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_project_id is null or not public.can_edit_project(p_project_id) then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  update public.project_google_oauth_connections
  set
    status = 'revoked',
    refresh_token = '',
    access_token = null,
    access_token_expires_at = null,
    updated_at = now()
  where project_id = p_project_id
    and status = 'active';

  if to_regclass('public.project_search_console_properties') is not null then
    execute $sql$
      update public.project_search_console_properties
      set
        is_active = false,
        updated_at = now()
      where project_id = $1
        and is_active = true
    $sql$
    using p_project_id;
  end if;

  if to_regclass('public.project_analytics_properties') is not null then
    update public.project_analytics_properties
    set
      is_active = false,
      updated_at = now()
    where project_id = p_project_id
      and is_active = true;
  end if;

  return true;
end;
$$;

grant execute on function public.fn_disconnect_project_google_oauth(integer) to authenticated;

do $$
begin
  if to_regclass('public.project_search_console_properties') is not null then
    alter table public.project_search_console_properties
      add column if not exists google_connection_id bigint null
        references public.project_google_oauth_connections(id) on delete set null;
  end if;
end $$;
